### PR TITLE
fix #925:Adding splash screen

### LINKED ISSUE #925: White screen persisting for a short duration after opening app
**Summary:** 

When opening the app, a white screen is shown for a certain duration of time.

**Steps to reproduce:** 

1)Run the application

**Expected behaviour:** 

The white screen should be replaced by a splash screen containing the logo of the application.

**Observed behaviour:** 

The white screen persists.

**Screenshots:** 

I would like to work on this.

### PR DESCRIPTION
**Pull request by AkshGautam**
fix #925 
@therajanmaurya @tarun0  Please review.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
@luckyman20 regarding the addition of Mifos text under the logo. I read about it and found out that one of the correct methods of adding a splash screen is by making a drawable.The drawable does not support a text view so either I have to add an image with text "mifos"  or either I could make a layout file as a splash screen which launches first and remains for a duration but that is not an ideal practice. What are your views?

**Comment by luckyman20** [comment]
@AkshGautam I have checked the material guidelines and it is written that try avoiding text views. So I think you are right. But I think you can choose more vibrant background color (cool and calm color but blue only).

**Comment by luckyman20** [comment]
@AkshGautam You can try using `#29B6F6` or `#00B0FF`

**Comment by AkshGautam** [comment]
@luckyman20 sure would try that out! looks better

**Comment by AkshGautam** [comment]
we could also try for rotating icon or some other animation as well. I have changed the color.

**Comment by luckyman20** [comment]
@AkshGautam Can you try and show some of the animations?

**Comment by AkshGautam** [comment]
Sure.I would do that

**Pull request merged**
