### PR TITLE
fix: Issue #778 - Added simple Scrollbar for clients/groups/centers list

### LINKED ISSUE #778: Requesting for Scrolling Bar on Client/Group/Centers Listing
Also There is a need to implement a Scrolling Bar on Client/Group/Centers Listing so as to show the approximate the position and length of the listing, So this can can positively impact the Navigation through the Listing.
Thanks

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #778 

screenshot_1516616121
Clients

screenshot_1516617634
Groups

screenshot_1516617744
Centers

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

@therajanmaurya Please review it !!
@edcable Thanks for giving out me chance. It was a very knowledgeable experience for me.

### CODE REVIEW

**Comment by iml-v** [comment]
@luckyman20  i think you should add ScrollBar Track and ScrollBar Thumb in Scrollbar style because without it scrollbar does not looks user friendly .What you say @luckyman20 .

**Comment by luckyman20** [comment]
@iml-v That is very true, I agree to you but I am waiting for the @therajanmaurya to approve it.

**Comment by iml-v** [comment]
@luckyman20  what is progress on this ,if you have not implemented yet then should I take this issue and implement (only if you have not  implemented)

**Comment by luckyman20** [comment]
@iml-v I am waiting for mentors view on it. And I have clearly mentioned that I have implemented a simple scrollbar, later on you can go for making it more stylish.

**Comment by iml-v** [comment]
@luckyman20  thanks for clarifying ,I thought if there is need of any help so

**Pull request closed without merging**
