### PR TITLE
restructured: xml files for regex fragment*.xml

### LINKED ISSUE #1871: Warnings on xmls files for fragment regex
**Summary:** 
Warnings on xmls files for fragment regex

**Steps to reproduce:** 
By adding respective tags assignments

**Observed behaviour:** 
Removed warnings from XMLs

### PR DESCRIPTION
**Pull request by avinash14022002**
Fixes #1871 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
Review and merge the code of this issue [Bintray ](https://github.com/openMF/android-client/issues/1864#issue-1173179754) then merge above code.

**Comment by avinash14022002** [comment]
@danishjamal104 @iamsh4shank ,
please review the PR,

### PR Solves

- The deprecated dependency of the XMLs files for regex fragment*.xml

**Review by danishjamal104 — COMMENTED** [review]
Have you tested if this code refactoring is not breaking any UI?

**Comment by danishjamal104** [comment]
> Have you tested if this code refactoring is not breaking any UI?

@avinash14022002 need you input.

**Comment by avinash14022002** [comment]
> > Have you tested if this code refactoring is not breaking any UI?
> 
> @avinash14022002 need you input.

Sorry for delay
No UI break detected

**Review by danishjamal104 — APPROVED** [review]
LOOKS GOOD

**Comment by danishjamal104** [comment]
@iamsh4shank merge this. Thanks :)

**Pull request merged**
