### PR TITLE
Fixes #1738 : Previous search results unnecessarily showing error fixed

### LINKED ISSUE #1738: Previous search results showing unnecessarily in Search Fragment.
**Summary:** 

Previous search results showing unnecessarily if there is no current search result found along with alert dialog in Search Fragment.

**Steps to reproduce:** 

1. Search for something in search Fragment of Dashboard Activity.
2. Once, results are visible search for something else which don't have any matches.

**Expected behaviour:** 

Previous results should clear and alert dialog appears.

**Observed behaviour:** 

Previous results are as they are and alert dialog box appears.

**Device and Android version:** 

Any

https://user-images.githubusercontent.com/67901968/106143062-47a74580-6198-11eb-883c-48eeeec95833.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1738 

Previous search results cleared if no current search results are found in Search Fragment.

https://user-images.githubusercontent.com/67901968/106143596-03687500-6199-11eb-97b4-6c269fb7b12f.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — CHANGES_REQUESTED** [review]
@NikunjGarg2000 I think it would be better if we make snackbar like that for empty search instead of alert dialog as it would match with UI of app

**Comment by NikunjGarg2000** [comment]
@PatelVatsalB21 , yes you are right but the issue is not about that so should change in this pr only or should raise a new issue. Please guide.
Thank you.

**Comment by PatelVatsalB21** [comment]
> @PatelVatsalB21 , yes you are right but the issue is not about that so should change in this pr only or should raise a new issue. Please guide.
> Thank you.

If you change in this pr it might solve both problems. But if you find it appropriate making new pr then go for it. Thank you😊

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Pull request closed without merging**
