### PR TITLE
Fix converting date to medium format.

### PR DESCRIPTION
**Pull request by TypicalGitHubUser**
See #455

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@TypicalGitHubUser Can you please post the screen shot.

**Comment by TypicalGitHubUser** [comment]
@therajanmaurya 
locale "ca"

device-2017-02-22-190421

**Comment by therajanmaurya** [comment]
Looks good. Can you please follow the commit style guide. check project wiki.
and squash your multiple commits into one.

**Comment by TypicalGitHubUser** [comment]
@therajanmaurya
Unfortunally, I don`t know how to squash my commit and merge commit with master.
Can you suggest something or should I create new PR?

**Comment by therajanmaurya** [comment]
@TypicalGitHubUser There is many guides. You can follow anyone http://stackoverflow.com/a/5189600/3176277 or https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/.  If need any help ping me on gitter.

**Comment by TypicalGitHubUser** [comment]
@therajanmaurya 
Thanks for your help. I`ve squashed them and PR is ready to apply.

**Pull request merged**
