### PR TITLE
Fix Issue #774: Client Name is displayed as null

### LINKED ISSUE #774: Client Name is displayed as null if Client Type is "ENTITY"
image

### PR DESCRIPTION
**Pull request by AkshGautam**
Fix #774 
@therajanmaurya @tarun0  Please review.No client is being displayed as null now.
The Json response of the client being displayed as null and the other can clearly be seen the json response captured in the gist.
https://gist.github.com/AkshGautam/2295e7304b9d0a32d75110e2d677eebb
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@AkshGautam Please add screenshot also

**Comment by AkshGautam** [comment]
**Before**

screenshot_2018-03-07-18-10-20

**After**
screenshot_2018-03-07-18-23-16

**Comment by luckyman20** [comment]
@AkshGautam Please change the commit message to - `fix: Issue #774 - Client Name is displayed as null`

**Comment by AkshGautam** [comment]
@luckyman20 done

**Pull request merged**
