### PR TITLE
Add Capture and Upload Sign feature

### PR DESCRIPTION
**Pull request by tarun0**
Fix: #705 

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by tarun0** [comment]
@therajanmaurya Please review.

sign

**Comment by therajanmaurya** [comment]
@tarun0 I want a change in UI, We are supporting API 25 and above and using Design Library.
Please use [BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html) for showing `Reset` and `From Gallery` and Add menu button `Upload`.

**Comment by tarun0** [comment]
@therajanmaurya We are not yet using Support Library version 25 in the app: https://github.com/openMF/android-client/blob/master/build.gradle#L15  Should I change the version?

**Comment by therajanmaurya** [comment]
No problem, update to 25 and make the changes accordingly

**Comment by tarun0** [comment]
@therajanmaurya I tried to use version 25 but it crossed the 65K limit. I enabled ``multi-dex` but it threw the error `Build-in class shrinker and multidex are not supported yet.` 
However, the shrinker is already set to false.

I've asked the same at SO: https://stackoverflow.com/questions/45009014/shrinker-already-set-to-false-still-build-in-class-shrinker-and-multidex-are-no

**Comment by tarun0** [comment]
@therajanmaurya I made the changes. The UI now is as below:

sign

**Pull request merged**
