### PR TITLE
Handling EditText hint text and items in option menu

### PR DESCRIPTION
**Pull request by karsai1993**
Fix: EditText hint text can be read fully.
EditText hint text cannot be read fully.

Fix: Items in option menu are shown in all fragments, only disabled in certain case.
Items in option menu are not stable as they become invisible in certain fragments and after coming back to DashboardActivity, the items in option menu does not get refreshed to the original status.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
Make sense, Thanks for the PR. Can you please follow the commit style guideline https://github.com/openMF/android-client/wiki/Commit-Style-Guide

**Comment by karsai1993** [comment]
@therajanmaurya , understood. I will do so in the future.
As you can see their is another one issue: #476 referenced here. I did so because my solution fixes the problem described there. My explanation is detailed in that issue. Is it a problem from your point of view that I did not wait for your response regarding that issue?

**Comment by therajanmaurya** [comment]
Can you please make the commit message like 
fix: {you message}
It will great you can.

**Comment by karsai1993** [comment]
Could you please help how I can edit the commit text? Or you mean that the name of the pull request should be Fix: Handling EditText hint text and items in option menu?

**Comment by therajanmaurya** [comment]
Here you go https://help.github.com/articles/changing-a-commit-message/

**Comment by karsai1993** [comment]
Done, thanks for your help!

**Comment by therajanmaurya** [comment]
Great work so far. I appreciate. We are happy to have you.
Welcome to community @karsai1993.

**Comment by karsai1993** [comment]
Thanks @therajanmaurya . It is my pleasure.

**Pull request merged**
