### PR TITLE
Address linter warnings regarding hardcoded text

### PR DESCRIPTION
**Pull request by zwliew**
If displayed during runtime, move hardcoded text to the
strings resources.

Otherwise (placeholder text), mark the text attributes with
the tools namespace to indicate that the text will not be
used during runtime.

Issue: #412
GCI task: 5686335463489536

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AbhilashG97** [comment]
@zwliew, amazing work ! But you made a few errors. Could you please correct them ? 

In the **row_loan_transaction_items.xml** and **view_account_accordian_section.xml** files could you please revert the changes you have made, because these will get rendered in real-time when the app runs.
 
Please look [here](https://github.com/JoanZapata/android-iconify) for more information.

And lastly could you also change the **android:text** attribute to **android:hint** attribute inside the EditText view in **dialog_fragment_charge.xml** file.
 
Apart form that you did a great job. :+1:

**Comment by zwliew** [comment]
Ah, I see. I've made the appropriate changes to the patch above, with the suggestions you made.

**Comment by AbhilashG97** [comment]
@zwliew, everything looks good now.

**Comment by AbhilashG97** [comment]
Hello @zwliew, 

Can you please open your pull request so that it can be merged later on ?  

Thank you. :smile:

**Pull request closed without merging**
