### PR TITLE
Fixed #1586 date picker bug

### LINKED ISSUE #1586: Datepicker doesn't retain user selected date throughout the app.
**Summary:** 
When date is selected from datepicker it is updated in textview but not in datepicker, when user again clicks datepicker it opens with current date.

**Steps to reproduce:** 

 Select date in any activity and again open datepicker

**Expected behaviour:** 

Datepicker should show user selected date.

**Observed behaviour:** 

Datepicker shows current date

**Device and Android version:** 

Lenovo Tab 7
Android 7 

**Screenshots:** 

GIF-201203_114837

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1586 
Now date picker retains user selected date throughout app and also fixed a typo.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
@robustTechie can you please review this change. Thank you

**Comment by robustTechie** [comment]
@PatelVatsalB21 can you share the screenshot after the changes. 👍

**Comment by PatelVatsalB21** [comment]
Sure.

**Comment by robustTechie** [comment]
> Sure. But plz wait for some time

Yeah, no problem :)

**Comment by PatelVatsalB21** [comment]
I updated pr, please review it.

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved

**Pull request closed without merging**
