### PR TITLE
Fixes #1766: Toast Redundancy fixed in SavingsAccountActivateFragment

### LINKED ISSUE #1766: Toast Redundancy in Saving Account Activate fragment
**Summary:** 
When user activates saving or recurring account, after successful activation, to notify it to user both Toast and Snackbar are made.

**Steps to reproduce:** 
1 Open Saving Account Details
2 Activate Account

**Expected behaviour:** 
Only one of Toast or Snackbar should be visible

**Device and Android version:** 
Any

**Recording:** 

https://user-images.githubusercontent.com/70195106/107880901-b100b580-6f07-11eb-8cf3-2bbbe093cfda.mp4

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1766 

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by danishjamal104** [comment]
@PatelVatsalB21 , please add a video. Thanks :)

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by PatelVatsalB21** [comment]
@danishjamal104 Just a toast message is removed, is it necessary to add video for it? If yes then I will make it or is it ok? . Thanks

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
