### PR TITLE
ImageLoadingAsyncTask to Picasso, for image loading in different thread.

### PR DESCRIPTION
**Pull request by therajanmaurya**
Earlier, there was image loading using ImageLoadingAsyncTask in main Thread in `ClientDetailsFragment` that makes the application glitchy. I have updated the project to use okhttp3 and also Picasso for image loading in different thread and remove unnecessary Progress Bar and Image loading much faster  than ImageLoadingAsyncTask . This removes a lot of unnecessary AsyncTask code.

For future image loading any where in application just do in few lines of code 

`private Picasso picasso;`

initialize in onCreate or onCreateView 
```java
picasso = new Picasso.Builder(getActivity())
			    .downloader(new OkHttp3Downloader(new OauthOkHttpClient().getOauthOkHttpClient()))
			    .build();
```
and load the image in ImageView 

```java
picasso.load(imageUrl)
			.error(R.drawable.ic_launcher)
			.centerCrop()
			.into(iv_clientImage);
```

#OauthOkHttpClient.class

```java
public class OauthOkHttpClient
{
	public OkHttpClient getOauthOkHttpClient()
	{
		OkHttpClient okClient = new OkHttpClient.Builder().addInterceptor(new Interceptor()
		{
			@Override
			public Response intercept(Chain chain) throws IOException
			{
				Request newRequest = chain.request().newBuilder()
						.addHeader(ApiRequestInterceptor.HEADER_TENANT, "default")
						.addHeader(ApiRequestInterceptor.HEADER_AUTH, PrefManager.getToken())
						.addHeader("Accept", "application/octet-stream")
						.build();
				return chain.proceed(newRequest);
			}
		}).build();
		return okClient;
	}
}
```

### CODE REVIEW

**Comment by ishan1604** [comment]
Please add license header to the new files that you added to the project. 
```
/*
 * This project is licensed under the open source MPL V2.
 * See https://github.com/openMF/android-client/blob/master/LICENSE.md
 */

```

**Comment by therajanmaurya** [comment]
Okay,I will do it. 
can you please tell me which time zone are you in.
Thanks.

**Comment by ishan1604** [comment]
Haha :smile: 
IST

**Comment by therajanmaurya** [comment]
Thanks :smile:

**Comment by therajanmaurya** [comment]
@ishan1604 Can I add new features ?

**Comment by ishan1604** [comment]
@therajanmaurya Like ?

just to point out,

**Comment by therajanmaurya** [comment]
Like Report Creation, More Client info , More Saving Account Info , More Loan Info .

**Comment by ishan1604** [comment]
Sounds interesting to me! You have a go ahead from my side. 

But I'd still like you to put this idea on the Mailing list and take a vote on what the community actually wants, so that you only work on something that gets used and not just sits in the app as a bloatware. 

I have another task for you, would you like to connect with me here https://gitter.im/openMF/mifos

**Comment by therajanmaurya** [comment]
Okay, Thanks I am connected to [https://gitter.im/openMF/mifos ](https://gitter.im/openMF/mifos ).
I forgot the **Search Option**

**Pull request closed without merging**
