### PR TITLE
Fixes #1691: Offline Sync icon updated

### LINKED ISSUE #1691: Offline Sync icon change required
**Summary:** 
As we can see icon used for Offline sync is meant for Power On/Off
 
**Expected behaviour:** 
New icon required for Offline sync

**Device and Android version:** 
Any

**Screenshots:** 
ss

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1691 

ss

ss

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Review by NikunjGarg2000 — APPROVED** [review]
LGTM

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 it's ok if everyone not approves it. It is not mandatory. Let it be.

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 it is not mandatory to approve. Actually approval of member with write access only counts. But as @danishjamal104 has a good experience with this repo he requests changes and approves pr. So it is not necessary to for everyone to approve. I hope you got it. Thank you

**Comment by NikunjGarg2000** [comment]
OK @PatelVatsalB21 , I don't know that. I thought I was helping doing that and I only approved that code which I understood.

**Pull request closed without merging**
