### PR TITLE
create group,create client and create center 

### PR DESCRIPTION
**Pull request by nellyk**
i have done the screen and a few of the APIs, kindly merge this pull request as i continue to improve on it

### CODE REVIEW

**Comment by ishan1604** [comment]
Needs Squashing

**Comment by nellyk** [comment]
@ishan1604  how many commits should i have for it to be okay ?

**Comment by ishan1604** [comment]
Just 1

**Comment by nellyk** [comment]
@ishan1604  Thank you

**Comment by nellyk** [comment]
@ishan1604 it seems everytime i squash commits i have to resolve conflicts so i always end up with two commit , should i still send it with the two commits?

for Squashing and for merge conflicts?

**Pull request closed without merging**
