### PR TITLE
fix: The progress bar in Datatables of both Clients and Groups loads endlessly.

### PR DESCRIPTION
**Pull request by AbhilashG97**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

**Issue Reference :**
#597

**After fixing the issue-**
The progress bar now doesn't load endlessly on going back from a Datatable to the list of Datatables.

videotogif_2017 03 21_18 24 19

### CODE REVIEW

**Comment by AbhilashG97** [comment]
I have the required changes, please review my pull request. And kindly let me know if I have to make any further changes.

**Comment by therajanmaurya** [comment]
@AbhilashG97 Can you please remove this line `((MifosBaseActivity) getActivity()).getActivityComponent().inject(this);` to `public View onCreateView()` from `public void onCreate()` and Let me know what happen.

**Comment by AbhilashG97** [comment]
@therajanmaurya, I made the suggested change, and there seems to be no difference in the behavior of the datatables, the endless loading is still not present, as expected. I am attaching the GIF of the application after I made the suggested change. The logs for the same can be found [here](https://gist.github.com/AbhilashG97/0bce56f603734e272f4dd9bb04b3181e). Also, should I apply these changes in the pull request ? Kindly let me know.

videotogif_2017 03 28_18 40 11

**Comment by therajanmaurya** [comment]
Do one more thing, instead of initializing the `subscriptions = new CompositeSubscription();` in `attachView`, remove `subscriptions.unsubscribe();` from `detachView` and add `subscriptions.clear();`.
Let me know.

**Comment by AbhilashG97** [comment]
@therajanmaurya, I have made the suggested changes, and the progress bar doesn't load endlessly. Please let me know if I have to make any further changes. GIF for the same can be found below.

**GIF-**

videotogif_2017 04 24_18 43 35

**Pull request merged**
