### PR TITLE
style: Added French Translation

### PR DESCRIPTION
**Pull request by Danki567**
I added a French (fr) Translation

### CODE REVIEW

**Comment by AbhilashG97** [comment]
Hello @Danki567, 

The Travis CI build for your pull request is failing, can you please look into that ? Also can you please rename ```values-fr-DanielGenkin.xml``` to ```strings.xml``` ? 

If you need any help, please let me know I'll be glad to assist you.

**Comment by Danki567** [comment]
Hello, thank you for the feedback. I renamed the file to strings.xml but I have looked into the travis build failing and I can't find out why. I tried to download and open my project, as well as the mifos version, in android studio which also fails. 

**Android studio error**
Compilation is not supported for following modules: android-client. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

Does this have anything to do with my translation? Thanks in advance

**Comment by AbhilashG97** [comment]
Hello @Danki567, 

It seems that the error is related to Android Studio, as you have correctly pointed out. Do you have the latest version of Android Studio installed ? If not can you please install the latest version of Android Studio. 

Please refer to this [stackoverflow post](https://stackoverflow.com/questions/28668252/android-studio-error-unsupported-modules-detected-compilation-is-not-supported) which contains further information regarding your issue. 

Also, we only accept a single commit per pull request, so you will have to [squash](https://github.com/openMF/android-client/wiki/Git-&-Github) all your commits into a single commit. 

If the issue persists or if you need any help with squashing your commits, please let me know. I'll be glad to help you. : )

**Comment by Danki567** [comment]
Hello, Travis seems to be working now! Is there a way to squash the commits without using the github console

**Comment by Danki567** [comment]
Ok I figured out how to squash the commits. Thank you for the task

**Comment by therajanmaurya** [comment]
@Danki567 Thank you for your PR, Good work. I want little changes
Please translate every string that is present in default strings.xml (https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/res/values/strings.xml) in French.

As you will be done with translation, squash your commit in the single commit message and please follow commit guideline (https://github.com/openMF/android-client/wiki/Commit-Style-Guide) too.

**Comment by Danki567** [comment]
Ok how is this? Thank you

**Comment by AbhilashG97** [comment]
Hello @Danki567, 

Good job ! The pull request however still requires some minor changes, can you please make the following changes - 
1. Can you please squash your commits ? There still **two** commits in your pull request instead of **one**.
1. Please revert the change in ```gradle-wrapper.properties``` or don't include it in the pull request.
1. Please change your commit message to ```style: Added French Translation ```

Please let me know if you need any help, I'll be glad to assist you. : )

**Comment by Danki567** [comment]
I seem to have accidentally squashed to many commits, some of which weren't even mine. what should I do

**Comment by AbhilashG97** [comment]
Hello @Danki567, 

It's not a major issue, you easily undo the ```rebase```. Please look at this [stackoverflow post](https://stackoverflow.com/questions/134882/undoing-a-git-rebase) for more details. 

All you have to do, is find the ```HEAD``` from which the ```rebase``` began by using ```git reflog``` and then use the ```git reset``` command along with that ```HEAD``` to undo it, which has been described well in the above mentioned stackoverflow post. 

Also, please make sure that you **do not**  have any **uncommitted changes** while performing ```git reset --hard```, else you'll lose those uncommitted changes for good.

I have also noticed that you haven't addressed all the changes suggested above, can you please make make those changes. You need to make the following changes -

1. Please revert the change in ```gradle-wrapper.properties``` or don't include it in the pull request.
1. Please translate the string arrays.  The string array starts from the line number ```663``` in ``` android-client/mifosng-android/src/main/res/values/strings.xml``` file of your clone.

 If you need any help with anything, please let us know. : )

**Comment by Danki567** [comment]
I made the requested changes and here is the final version. Phewww :)

**Comment by therajanmaurya** [comment]
Good work 👍

**Pull request merged**
