### PR TITLE
Fixed the crashing of app after entering the passcode

### LINKED ISSUE #1896: App crashes after entering the passcode
**Summary:** 

App crashes when you enter the passcode.

**Steps to reproduce:** 

https://user-images.githubusercontent.com/94394661/220975822-89629426-882a-4eae-abfd-18bf4db8d6a8.mp4

**Expected behaviour:** 

As soon as the passcode has been entered, the Home Screen should appear.

**Device and Android version:** 

Device : OnePlus Nord
Android 12

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1896 

https://user-images.githubusercontent.com/94394661/221224305-f9591083-30c5-4acc-ac9e-5441db116f7f.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
> Fixes #1896 
> 
> https://user-images.githubusercontent.com/94394661/221224305-f9591083-30c5-4acc-ac9e-5441db116f7f.mp4
> 
> 
> Please make sure these boxes are checked before submitting your pull request - thanks!
> 
> - [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
> 
> - [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
> 
> - [x] If you have multiple commits please combine them into one commit by squashing them.

Hi @Aditya-gupta99 ,
Create a separate PR for grade upgrade.

**Comment by avinash14022002** [comment]
@Aditya-gupta99 ,
Solve the merge conflict

**Comment by Aditya-gupta99** [comment]
@avinash14022002 i have solved the merge conflicts, kindly review them

**Comment by j0nimost** [comment]
@avinash14022002  Can this PR get reviewed and merged?

**Review by avinash14022002 — APPROVED** [review]

**Pull request merged**
