### PR TITLE
MIFOSAC-113 Important validations added, unimportant removed

### PR DESCRIPTION
**Pull request by vjs3**
Issues resolved in this PR are:
1.There were many unnecessary validation fields has been added to the create group, create client and create centers functionality, as I discussed with mentors compulsory fields should be same in both web as well as android interface, hence a solution involving it has been provided.
2.There was no validation for group's name (it is compulsory for a group to have some name, webapp contains it) which has been added too.

### CODE REVIEW

**Comment by ishan1604** [comment]
Please resolve the conflicts before sending the PR. 

Thanks

**Comment by vjs3** [comment]
I don't know how it is showing merge conflicts suddenly, considering I have created a separate branch and worked upon it!

**Comment by vjs3** [comment]
@ishan1604 on rebasing on my local repo I am unable to see merge conflicts, can you help me here a bit so that I can resolve it.I have a separate branch for this issue so I don't know why this conflict occurred?

**Comment by ishan1604** [comment]
Try merging master into your branch locally you might see the problem.

**Comment by vjs3** [comment]
@ishan1604 thanks your advice worked for me!Please review my new PR.

**Pull request closed without merging**
