### PR TITLE
Image downloading through glide instead of async task

### PR DESCRIPTION
**Pull request by top-gun007**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@top-gun007 This is not good way to open a PR, I am closing this PR for now and When you have completed PR then open new one.

**Comment by top-gun007** [comment]
@therajanmaurya I am really sorry about it can we discuss it on some other patform

**Comment by therajanmaurya** [comment]
Yeah come on gitter.

**Comment by top-gun007** [comment]
@therajanmaurya ok and thanks

**Pull request closed without merging**
