### PR TITLE
Fixes #1796: Scrolling behaviour applied to FAB

### LINKED ISSUE #1796: Feature: Adding scrolling behaviour to FAB
**Summary:** 
When user scrolls through list of Clients, Groups and Centers it is visble that FAB remains still, which is not responsive with UI.  There is difference between Image btn and FAB, as FAB is available with some features to `show()` and `hide()`. It should be implemented for better User Experience.

**Steps to reproduce:** 
1 Open Clients
2 Scroll the List

**Expected behaviour:** 
Fab should show and hide with scroll changes.

**Device and Android version:** 
Any

**Recording:** 

https://user-images.githubusercontent.com/70195106/109395970-49aa2300-7955-11eb-8e7e-014e156b5bf0.mp4

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1796

https://user-images.githubusercontent.com/70195106/109396289-cb4e8080-7956-11eb-8943-b684fdf8d9c0.mp4

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by Grandolf49** [comment]
Hey @PatelVatsalB21 can you resolve the merge conflict so that we can merge this?

**Comment by iamsh4shank** [comment]
Hey @PatelVatsalB21 can you fix the merge conflicts so that we can merge the PR :)

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
