### PR TITLE
Fixes #1726: Keyboard closed at last edit text in create client, create group and create center fragments 

### LINKED ISSUE #1726: Keyboard related issue
**Summary:** 

Soft keyboard doesn't close after the last edit text in create client, center and group fragments.

**Steps to reproduce:** 

1)Go to any of create client, create group or create center fragments.
2)Type anything in the last edit text available and press next.

**Expected behaviour:** 

On pressing next, keyboard should collapse and the last edit text shouldn't be in focus

**Observed behaviour:** 

On pressing next in the last edit text, the keyboard doesn't collapse.

**Device and Android version:** 

RedMi Note 8 Pro
Android 9

**Screenshots:** 

https://user-images.githubusercontent.com/52701183/105319643-2ae49e00-5beb-11eb-9fd4-9f2a864be7be.mp4

### PR DESCRIPTION
**Pull request by Abhinavtdk**
Fixes #1726

https://user-images.githubusercontent.com/52701183/105319810-65e6d180-5beb-11eb-906d-5d7c3179f791.mp4

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — COMMENTED** [review]
@Abhinavtdk please add issue number in pr heading at the beginning. For reference please go through other prs.

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
