### PR TITLE
restructured: xml files for regex item*.xml

### LINKED ISSUE #1869: Warnings on xmls files for item regex
**Summary:** 
Warnings on xmls files for item regex

**Steps to reproduce:** 
By adding respective tags assignments

**Observed behaviour:** 
Removed warnings from XMLs

### PR DESCRIPTION
**Pull request by avinash14022002**
Fixes #1869 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
Review and merge the code of this issue [Bintray ](https://github.com/openMF/android-client/issues/1864#issue-1173179754) then merge above code.

**Review by danishjamal104 — COMMENTED** [review]
Are you sure this wont break any UI?

**Comment by avinash14022002** [comment]
> Are you sure this wont break any UI?

@danishjamal104 ,
No UI break detected

**Review by danishjamal104 — APPROVED** [review]
LOOKS GOOD

**Comment by danishjamal104** [comment]
@iamsh4shank merge this. Thanks :)

**Pull request merged**
