### PR TITLE
Refactor: Migrate CreateNewCenterFragment to Jetpack Compose

### LINKED ISSUE #2077: Refactor: Migrate CreateNewCenterFragment to Jetpack Compose
Summary:

Transitioning from XML to Jetpack Compose offers advantages such as adopting a declarative UI approach, ensuring type-safe UI development, and minimizing boilerplate code.

### PR DESCRIPTION
**Pull request by ashutosh-kumar-kushwaha**
Fixes #2077

Please Add Screenshots If there are any UI changes.

Screenshot_20240402-214705_MifosXDroid

Screenshot_20240402-214723_MifosXDroid

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
I tested the functionality, It is not same as it was implemented in XML and also search functionality is broken. I always get no result.

**Comment by ashutosh-kumar-kushwaha** [comment]
> I tested the functionality, It is not same as it was implemented in XML and also search functionality is broken. I always get no result.

The Create Center functionality is broken in XML as well.

**Comment by ashutosh-kumar-kushwaha** [comment]
> I tested the functionality, It is not same as it was implemented in XML and also search functionality is broken. I always get no result.

The Create Center functionality is broken in XML as well. Always gives HTTP 400 or 500.

The progress bar was implemented inside the screen in XML, whereas I implemented it within a Dialog in Compose. I will fix that. Apart from this, I did not see any other differences.

**Comment by therajanmaurya** [comment]
Can you please upload the before and after videos? I want to include this implementation in our codebase but we must maintain the code quality. 

Also check why always API gives No search found but in development branch it does return on searc

**Comment by ashutosh-kumar-kushwaha** [comment]
> Can you please upload the before and after videos? I want to include this implementation in our codebase but we must maintain the code quality.

Before -

https://github.com/openMF/android-client/assets/109234707/5d62caa4-a78b-4392-9d87-8d477077764f

After -

https://github.com/openMF/android-client/assets/109234707/75d392ba-719a-4cc7-9fdc-b8b6d801b66f



> Also check why always API gives No search found but in development branch it does return on searc

The SearchScreen one is a different PR. This PR is for CreateNewCenterFragment.

**Pull request closed without merging**
