### PR TITLE
Fixed #1611: BackPressed error removed

### LINKED ISSUE #1611: onBackPressed error
**Summary:** 
When user is on create client, group or centre screen, if he presses back Toast comes up and then if again clicks back it navigates to search fragment.

**Steps to reproduce:** 
1 Go to Create Client, Group or Center
2 Press back 2 times 

**Expected behaviour:** 

It should first navigate to search fragment on one back press then on 2nd backpress it should show toast

**Device and Android version:** 
Lenovo Tab 7
Android 7

GIF-201209_174449 1

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1611 

Check added that ensure proper working and only shows toast when on SearchFragment

GIF-201209_175855 1

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — COMMENTED** [review]
LGTM
Just wait for the build to be completed.

**Review by danishjamal104 — APPROVED** [review]

**Comment by PatelVatsalB21** [comment]
@danishjamal104 build is complete. Please review it.

**Comment by PatelVatsalB21** [comment]
Thank you :) 👍

**Review by robustTechie — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
