### PR TITLE
fixing squashing issue- added the ability to create center, group and client

### PR DESCRIPTION
**Pull request by nellyk**
@ishan1604  hope this resolves the squash issue , though it seems i squashed so many commits, :-(

Can you kindly advice me on the best way to resolve this issue.

### CODE REVIEW

**Comment by nellyk** [comment]
@ishan1604 i was able to finally squash my commits into one and still preserve all the other commits :-)

**Comment by ishan1604** [comment]
@nellyk Excellent Job Squashing. I always knew you were self motivated enough to find your way out of problems. :+1: 
I am sorry for not replying to your previous comments, it was too late here as per the IST.

**Comment by nellyk** [comment]
Thank you @ishan1604 , i have updated the pull request.

**Comment by ishan1604** [comment]
Thanks for the Pull Request.

**Comment by nellyk** [comment]
@ishan1604  thank you :-)

**Pull request merged**
