### PR TITLE
Fix #1176 Run Report List display incosistent

### LINKED ISSUE #1176: Run Report List display incosistent
**Summary:** 
Run Report output display report in uncosistent view, With Capital and Small Letters in some text. Child Offices start with dots at beginning of office name.

**Steps to reproduce:** 
Open Run report 
Select one of the report let **Active Clients**
Fill the credential and Click Run Report

**Expected behaviour:** 
Report should display in consistence behaviour and view

**Observed behaviour:** 

Some Text display in Capital letter other in Small letters, Child office start with dots **...**, Colum items coalesce 

**Device and Android version:** 

Android version 9.0

**Screenshots:**

### PR DESCRIPTION
**Pull request by elirehema**
Run Report List display incosistent

Fixes #1176 

**Screenshot**
ezgif com-optimize

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by elirehema** [comment]
Hi @santoshconflux can you check this PR

**Comment by AbhilashG97** [comment]
Hello @elirehema,

Can you please fix checkstyle issues in your pull request?

**Comment by elirehema** [comment]
Hi @AbhilashG97 i have updated PR. You can review now. Is it possible to review PR's on time ?.  Created pr on November 2019 review on June 2020

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the java file has now been migrated to kotlin

**Pull request closed without merging**
