### PR TITLE
New icon added for individual_collection_sheet and typo fixed in run reports

### LINKED ISSUE #1623: Minor fixes in navigation drawer menu item
**Summary:** 

Icons for `IndividualCollectionSheet` and `CollectionSheet` is same which makes difficult to distinguish. Typo in Run Reports it should be `Run Reports` instead it is `RunReports`.

**Expected behaviour:** 

1. Different icon for different menu items.
2. It should be `Run Reports`

**Observed behaviour:** 

1. Same icons for `IndividualCollectionSheet` and `CollectionSheet`.
2. Typo in `RunReports`.

**Device and Android version:** 

* ANY

**Screenshots:** 

ss

### PR DESCRIPTION
**Pull request by danishjamal104**
Fixes #1623 

ss

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
Hey @danishjamal104 can i review and approve this pr? It will be first one for me.

**Review by robustTechie — CHANGES_REQUESTED** [review]
Hey, @danishjamal104 can you adjust the shape of the symbol, also can you put it in the same color order as other icons are :)

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
@danishjamal104 the button looks a little bit big as compared to other buttons. Please fix that so we'll merge it soon :)

**Comment by danishjamal104** [comment]
sorry I haven't updated the screenshot, let me update and then recheck it. Thanks :).

**Review by iamsh4shank — APPROVED** [review]

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Hey @danishjamal104  there are a few merge conflicts can you resolve it so we will merge it soon.

**Pull request closed without merging**
