### PR TITLE
Gradle was upgraded to version 7.6.1

### LINKED ISSUE #1914: The version of Gradle should be updated to the latest version
**Summary:** 

The version of Gradle should be updated to the latest version

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1914 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Aditya-gupta99** [comment]
@avinash14022002 Can u please review this PR.

**Comment by avinash14022002** [comment]
@Aditya-gupta99 did you clicked on migrate dialog option?

**Comment by Aditya-gupta99** [comment]
No

**Comment by Aditya-gupta99** [comment]
@avinash14022002 I used the git bash command

**Comment by avinash14022002** [comment]
I am asking for migrating for gradle.

**Comment by Aditya-gupta99** [comment]
@avinash14022002  I wrote the following command in git bash and modified the Gradle script by myself.
image

**Comment by Aditya-gupta99** [comment]
Okay, I will follow up with you

**Review by avinash14022002 — APPROVED** [review]

**Pull request merged**
