### PR TITLE
Removed Obsolete SDK_INT Version Checks

### LINKED ISSUE #1398: Obsolete SDK_INT Version Checks
**Summary:** 

There are some Obsolete SDK_INT check versions in the project which are unnecessary. This check flags version checks that are not necessary, because the minSdkVersion (or surrounding known API level) is already at least as high as the version checked for.  

Example:

image

These types of checks can be safely removed from the project.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #1398 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Grandolf49** [comment]
Hey @RajaVamsi11 You have 4 pmd violations. probably for all 4 file changes.

**Comment by RajaVamsi11** [comment]
Yes, How do I know where they are going wrong? I tried gradlew build but it didn't help.

**Comment by Grandolf49** [comment]
Did u try checking this file?
 **android-client/mifosng-android/build/reports/pmd/pmd.html**

**Comment by RajaVamsi11** [comment]
The reports folders is not creating when i run gradlew command

**Comment by Grandolf49** [comment]
@RajaVamsi11  okay let me check.

**Comment by Grandolf49** [comment]
@RajaVamsi11  there are 4 unused imports that's why it is failing

**Comment by RajaVamsi11** [comment]
@Grandolf49 Thanks. I will remove them and push the PR again.

**Comment by RajaVamsi11** [comment]
@Grandolf49 It worked.

**Comment by AbhilashG97** [comment]
Hello @RajaVamsi11,

Can you please correct your commit message so that it can be merged?

**Pull request merged**
