### PR TITLE
Implementing SplashScreen API to show splash Screens 

### PR DESCRIPTION
**Pull request by zaidazaize**
### Summary:
This commit migrates java code of `SplashScreenActivity` to `kotlin` and implements the new `SplashScreen API` of android to show SplashScreen on Android 12 and greater. The task is achieved by using `SplashScreenCompat` library.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by zaidazaize** [comment]
hey @avinash14022002 can you review my pull request.

**Comment by zaidazaize** [comment]
#1918

**Comment by zaidazaize** [comment]
Also Fixes #1863 @Grandolf49

**Comment by zaidazaize** [comment]
also fixes #1863

**Comment by avinash14022002** [comment]
Hi @zaidazaize ,
We would be dealing Kotlin conversion as separate issue.

**Comment by zaidazaize** [comment]
hey @avinash14022002 I have created new branch for migrating splash screen activity to kotlin #1919

**Pull request closed without merging**
