### PR TITLE
Fixes #1752 : Unnecessary running of Spinner.OnItemSelectedListener fixed

### LINKED ISSUE #1752: Unnecessary running of Spinner.OnItemSelectedListener on first time
**Summary:** 

Unnecessary running of Spinner.OnItemSelectedListener in NewIndividualCollectionSheetFragment and GenerateCollectionSheetFragment on the first time as user enters.
As shown in video onItemSelectedListener checks for office and staff  and calls presenter too as soon as user enters which is not necessary since user hasn't selected anything yet.

**Steps to reproduce:** 

1. Select Individual Collection Sheet or Collection Sheet from Navigation drawer.

**Expected behaviour:** 

It must not check for office since the list is set to select office.

**Observed behaviour:** 

It checks and run onItemSelctedListener though user hasn't selected anything.

**Device and Android version:** 

Realme X
Android 10

https://user-images.githubusercontent.com/67901968/107141176-1aebee80-694d-11eb-8bb2-b80d2b49b02f.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1752 

Just added a quick check using a boolean variable whether user is entering fragment first time or not.

https://user-images.githubusercontent.com/67901968/107141466-dbbe9d00-694e-11eb-9657-13f5b842ddfe.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 i have problem differentiating any changes from issue video. I can see progress bar for first time too in pr video also. Am i missing out something or am I right ?

**Comment by NikunjGarg2000** [comment]
@PatelVatsalB21 the progress bar is not under Spinner.onItemselectedListemer in code.
You are missing the toast message in issue video. At the first time when user enters when office is selected to select office only then while setOnitemSelectedListener called in setUi(), onItemSelectedListener runs automatically and checks whether user have selected something which is very obvious since it's first time that user hasn't interacted yet.

**Comment by PatelVatsalB21** [comment]
Yes I know that but I was concerned about 2 spinner calling 2 OnItemSelected two times. LGTM

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
