### PR TITLE
Fixes #1764 : No task view added to CheckerInboxFragment

### LINKED ISSUE #1764: Absence of No Task view in CheckerInboxFragment
**Summary:** 

When user apply filters in search bar of Checker Inbox Fragment and dialog returns a null list then there should be a no task view telling no task available according to filters applied.

**Steps to reproduce:** 

1. Open Navigation drawer and select checker inbox.
2. Select checker inbox again and apply filters for which nothing is available.

**Expected behaviour:** 

It should show a no task view.

**Device and Android version:** 

Any

https://user-images.githubusercontent.com/67901968/107842514-dd261480-6de9-11eb-9811-97faef3a687d.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1764 

https://user-images.githubusercontent.com/67901968/107857287-979e3180-6e53-11eb-8732-efe737fc13d9.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — CHANGES_REQUESTED** [review]
@NikunjGarg2000 as visible in video attached by you "Task list" is visible between dialog goes and "No Task"View comes in. Please fix it rest looks goods.

**Comment by NikunjGarg2000** [comment]
I had made necessary changes, @PatelVatsalB21 please check now. Thanks you.

**Comment by PatelVatsalB21** [comment]
Looks Good to me let @robustTechie review

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Pull request closed without merging**
