### PR TITLE
Fix #1458: Display Alert Dialog Box instead of Toast in Settings

### LINKED ISSUE #1458: Feature: Display Alert Dialog Box instead of Toast in Settings Activity
**Summary:** 
When the user toggle's on the Sync Survey button without the internet, a Toast is displayed. Instead, it should prompt the user to switch on the internet in order to sync surveys.

**Steps to reproduce:** 

1. Open App
2. Goto Settings
3. Switch off the internet
4. Toggle on the Sync Survey button

**Expected behaviour:** 

Instead of showing Toast message, the user should be prompted to switch on the internet. If the user does it, syncing starts otherwise the sync toggle button remains in the OFF state.

**Observed behaviour:** 

A Toast message saying **"Network is not available"** is dispalyed.

**Device and Android version:** 

Device - Samsung Galaxy S10e
Android Version - 10 (Android Q)
Custom ROM - Samsung One UI version 2.0

**Screenshots:** 

Screenshot_20200324-140820_MifosXDroid

### PR DESCRIPTION
**Pull request by Sachit1137**
Prompt User to connect to network inorder to sync data

Fixes #1458 

Please Add Screenshots If there are any UI changes.
Screen-Recording-20200329-163618

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by robustTechie** [comment]
Nice feature but instead of open settings button, retry button will be good, and in the alert message write something like "internet connection failed please on your mobile data connectivity". As opening a activity various time will make a overworking of a thread.

**Comment by Sachit1137** [comment]
Thanks for the feedback

**Comment by robustTechie** [comment]
@Sachit1137 also after enabling the data, again we need to switch off  and then switch on the preference switch button, please try to fix this also.

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
