### PR TITLE
ui-enhancement #1339 -  UI Enhanced for Login Activity

### LINKED ISSUE #1339: UI Enhanced for Login Activity
**Summary:** 

The UI for the login page is not looking so good , i tried out to revamp it with the same dependency.

**Before :** 
before login

**After** 
after login page

**Device and Android version:** 

I tested on physical device ( Samsung J700) and all the emulators and its looks great.

**Design:** 
loginpage revamped

### PR DESCRIPTION
**Pull request by rohanprasadofficial**
The files were change according to the issues templates and guidelines

Fixes #1339 

**Before**

**After**

a

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rohanprasadofficial** [comment]
@droidchef @naman14  can you please review it .

**Comment by rachittt** [comment]
why is there an addition of ```.iml``` file?

**Comment by rohanprasadofficial** [comment]
@rachittt  oh really sorry, i forgot to add it in .gitignore

**Comment by rohanprasadofficial** [comment]
@rachittt  will this passing for review ? or i need to change something ?

**Comment by rachittt** [comment]
> @rachittt will this passing for review ? or i need to change something ?

It will be reviewed but maintainers will definitely ask you to remove the addition of ```.iml``` file.

**Comment by rohanprasadofficial** [comment]
@rachittt  thank you , waiting for any response .

**Comment by robustTechie** [comment]
Also add screenshot as you made some UI enhancement so it will be better to check the changes here itself.

**Comment by rohanprasadofficial** [comment]
@robustTechie  added the screenshot , can you review it ?

**Comment by robustTechie** [comment]
LGTM :)

**Comment by rohanprasadofficial** [comment]
@droidchef  can you please look into this once ?

**Comment by Aditya-gupta99** [comment]
Closing this PR since the XML file has been updated

**Pull request closed without merging**
