### PR TITLE
fix MIFOSAC-119

### PR DESCRIPTION
**Pull request by prempalsingh**
Signed-off-by: Prempal Singh <prempal.42@gmail.com>

### CODE REVIEW

**Comment by prempalsingh** [comment]
@ishan1604 can you re-run the build? should work fine now.

**Comment by vjs3** [comment]
@prempalsingh I was already working on the same issue as you can see on JIRA[ here](https://mifosforge.jira.com/browse/MIFOSAC-119). Please only resolve unassigned issues so that repetetive work can be avoided.

**Comment by prempalsingh** [comment]
@vjs3 Sorry, didn't realize it was assigned to you. Will take care next time. :)

**Comment by ishan1604** [comment]
Build Fails please resend!

**Pull request closed without merging**
