### PR TITLE
enhance group names list's look

### PR DESCRIPTION
**Pull request by ahmed-fathy-aly**
MIFOSAC-132 now the group names list follow the material design two-line list specs
![Screenshot]
(http://i.imgur.com/FuJQWdr.png)

### CODE REVIEW

**Comment by ishan1604** [comment]
1. Its not MOFISAC it should be MIFOSAC
2. Please share a screenshot of any aesthetic changes you bring into the app.

Thank you

**Comment by ahmed-fathy-aly** [comment]
@ishan1604  Fixed the typo, sorry about that 
Here's how the groups looked before
![Screenshot]
(http://i.imgur.com/a1Ek843.png)

and here's how it looks now
![Screenshot]
(http://i.imgur.com/FuJQWdr.png)

**Comment by ishan1604** [comment]
Thanks for the PR

**Comment by ahmed-fathy-aly** [comment]
Thank you :)

**Pull request merged**
