### PR TITLE
Fixes #1740 and #1738: Snackbar added and unnecessary search results removed

### LINKED ISSUE #1740: UI enhancement possible in Search Fragment
**Summary:** 

UI enhancement possible in Search Fragment. If we search for something in Search Fragment of Dashboard Activity and no search results are found then an alert dialog box is shown. If instead of alert dialog, snackbar is shown it will look more good since it will match UI of app.

**Steps to reproduce:** 

1. Open the app.
2. In search Fragment search something for which no search results exists.

**Device and Android version:** 

Any

https://user-images.githubusercontent.com/67901968/106352268-8f98aa80-6307-11eb-919e-3199abea4f70.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1740  and #1738

https://user-images.githubusercontent.com/67901968/107414984-c907bc00-6b38-11eb-9d28-2ac3c6d9c827.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — COMMENTED** [review]
@NikunjGarg2000 would it be good if we change title of pr to something like "Snackbar added to Search fragment", it's just a suggestion what do you think?

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — CHANGES_REQUESTED** [review]
Merge changes in #1739 to #1741 PR, it would make things easier as there would be conflict while merging the PRs since both the PR are somewhat related. Thanks :).

**Comment by NikunjGarg2000** [comment]
Thanks @danishjamal104  for such a nice suggestion. Done with the changes.

**Review by robustTechie — APPROVED** [review]
LGTM

**Review by iamsh4shank — APPROVED** [review]

**Pull request merged**
