### PR TITLE
restructured: xml files for regex activity*.xml and dialog*.xml

### LINKED ISSUE #1873: Warnings on xmls files for activity regex and dialog
**Summary:** 
Warnings on xmls files for activity regex and dialog

**Steps to reproduce:** 
By adding respective tags assignments

**Observed behaviour:** 
Removed warnings from XMLs

### PR DESCRIPTION
**Pull request by avinash14022002**
Fixes #1873 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
Review and merge the code of this issue [Bintray ](https://github.com/openMF/android-client/issues/1864#issue-1173179754) then merge above code.

**Comment by avinash14022002** [comment]
@danishjamal104 @iamsh4shank ,
please review the PR,

### PR Solves

- The deprecated dependency of the XMLs of  regex activity*.xml and dialog*.xml

**Review by danishjamal104 — COMMENTED** [review]
@avinash14022002 does this PR include any functional change?

**Comment by avinash14022002** [comment]
> @avinash14022002 does this PR include any functional change?

No,
The PR only have UI dependency update and rearrangement of XMLs.

**Comment by avinash14022002** [comment]
> > @avinash14022002 does this PR include any functional change?
> 
> No, The PR only have UI dependency update and rearrangement of XMLs.

@danishjamal104 
No UI break detected

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by danishjamal104** [comment]
@iamsh4shank merge this. Thanks :)

**Pull request merged**
