### PR TITLE
fix: improved UI of dialog boxes

### LINKED ISSUE #1241: UI inconsistencies in the dialog box of uploading a document
## Summary 
UI inconsistencies in the dialog box of uploading a document.

## Steps to reproduce
Clients -> Any Client -> Menu -> Documents -> + on the top right

## Expected Behaviour
A dialog box with good UI should come up.

## Observed Behaviour
A dialog box with a weird alignment comes up.

## Device and Android Version
Mi A3, Android 9

### PR DESCRIPTION
**Pull request by laxyapahuja**
## Issue Fix
Fixes #1241

## 

##
- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
@luckyman20 @moksh-mahajan can you please have a look at this? :D

**Comment by rachittt** [comment]
@laxyapahuja I think it would be better if both the buttons have an icon, as it looks odd on a single button.

**Comment by laxyapahuja** [comment]
> @laxyapahuja I think it would be better if both the buttons have an icon, as it looks odd on a single button.

good idea @rachittt

**Comment by laxyapahuja** [comment]
@luckyman20 @rachittt updated :D

**Comment by luckyman20** [comment]
@laxyapahuja Upload screenshot for another dialog too.

**Comment by laxyapahuja** [comment]
> @laxyapahuja Upload screenshot for another dialog too.

done :D

**Pull request merged**
