### PR TITLE
feat : added sweet-error for handling UI errors

### LINKED ISSUE #946: Adding sweet-error library support
**Summary:** 

Addition of library Sweet error Library across the application.

### PR DESCRIPTION
**Pull request by mohak1712**
fixes #946 

whatsapp image 2018-03-30 at 17 08 29 1
whatsapp image 2018-03-30 at 17 08 29 2
whatsapp image 2018-03-30 at 17 08 29 3
whatsapp image 2018-03-30 at 17 08 29 4
whatsapp image 2018-03-30 at 17 08 29 5
whatsapp image 2018-03-30 at 17 08 29 6

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mohak1712** [comment]
@therajanmaurya  please review

**Comment by luckyman20** [comment]
@mohak1712 Please fix the Travis Error

**Comment by mohak1712** [comment]
@luckyman20 i have fixed the Travis error

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the java file has now been migrated to kotlin

**Pull request closed without merging**
