### PR TITLE
Added margin in Group details activity

### LINKED ISSUE #1192: Add Margin to GroupActivity [GCI]
**Summary:** 

This task involves adding start and end margin to `GroupActivity` 

**Steps to reproduce:** 
- Open navigation drawer
- Click on Groups
- Click on any individual group from the list
- You can see that the details screen does not have the required start and  end margin

**Screenshots:**

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #1192 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@santoshconflux @luckyman20 @jddeep @harshinde07 Please review and approve. Thanks.

**Comment by luckyman20** [comment]
@PiyushSharma99 Attach screenshot too.

**Comment by PiyushSharma99** [comment]
@luckyman20 Added screenshot. Thanks!

**Comment by PiyushSharma99** [comment]
@luckyman20 Please review and approve. @jddeep Could you please approve my submission on the gci portal?

**Comment by luckyman20** [comment]
Push the changes to `development` branch not to `master` branch.

**Comment by PiyushSharma99** [comment]
@luckyman20 How can I change this now? I mean change the base branch where I want to push the changes. Do i open a new PR?

**Comment by PiyushSharma99** [comment]
@luckyman20 There is no development branch!

**Comment by luckyman20** [comment]
@PiyushSharma99 Sorry, my bad. This project doesn't have that. Just fix up the commit title and you would be good to go.

**Comment by PiyushSharma99** [comment]
Done :+1: @luckyman20

**Pull request merged**
