### PR TITLE
fix: currency symbol before amount

### LINKED ISSUE #1112: Add currency symbol in Account Summary
**Summary:** 

Need to add currency symbol with the amount whenever charges or balance are mentioned in the account summary. This would make it easier for the user and cause less confusion.

**Steps to reproduce:** 

Open a client, expand any account (loan or savings) and click on 
it to get to account summary.

**Screenshots:** 
Screenshot_20190309-214235

### PR DESCRIPTION
**Pull request by laxyapahuja**
## Issue Fix
Fixes #1112 

##

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
hi @laxyapahuja, don't you think it'll be a big task to redo what you've done, if we someday have to change the currency (because there is no official information if we are going with USD). 
@luckyman20 your views ?

**Comment by laxyapahuja** [comment]
> hi @laxyapahuja, don't you think it'll be a big task to redo what you've done, if we someday have to change the currency (because there is no official information if we are going with USD)?
> 
> @luckyman20 your views ?

hey @rachittt, I asked a mentor what the main currency of the app is going to be. The answer was USD.

**Comment by laxyapahuja** [comment]
If @luckyman20 agrees with what you're saying, I'll make the code responsive to any currency.

**Comment by PiyushSharma99** [comment]
> If @luckyman20 agrees with what you're saying, I'll make the code responsive to any currency.

@laxyapahuja https://github.com/openMF/android-client/pull/1228#discussion_r361324064

**Comment by luckyman20** [comment]
@laxyapahuja Please extract the currency symbol (or currency code in case there is currency symbol is not available) from API.

**Comment by rachittt** [comment]
@laxyapahuja if we don't get a response within 2 days, we will have to close this PR because it is restricting other contributors from working on it.

**Pull request closed without merging**
