### PR TITLE
Upload an Image from gallery to update client's profile picture.

### PR DESCRIPTION
**Pull request by pandilladivya**
Below are the screenshots of the app running

### CODE REVIEW

**Comment by pandilladivya** [comment]
Please review my code :)

Thank You!

**Comment by pandilladivya** [comment]
Please review my code #203 
Thank you!

**Comment by ishan1604** [comment]
needs merge conflicts resolution.

**Comment by pandilladivya** [comment]
@ishan1604 Can you please tell me what do you exactly mean by merge conflicts?

Thank you!

**Comment by ishan1604** [comment]
Pull the latest master branch and rebase your branch against it and then send the pull request again.

**Comment by pandilladivya** [comment]
Thank you...I will do that right away :)

**Comment by pandilladivya** [comment]
Hi,
I have rebased the branch and the solved merge conflicts

Kindly refer to the issue here #210

**Pull request closed without merging**
