### PR TITLE
Fixes #1568 Infinite refresh issue resolved

### LINKED ISSUE #1568: Swipe refresh goes into infinite refresh in Centers section
**Summary:** 
On returning to Centers Section after pressing the back button on any screen leads to infinite refresh with no change in data, also the same happens when we disconnect the internet and return back.

**Steps to reproduce:** 
1. Navigate to `Centers` using the option in `Navigation Drawer`
2. After data is loaded click on `FAB` in the bottom right.
3. Now press the back button twice to return back to `Centers Screen`
4. Observe the refresh icon on `Center-Top` of the screen.

**Expected behaviour:** 
* Possibility 1: No refresh should be triggered on returning back 
* Possibility 2: Refresh should be triggered and should stop once the data is loaded

**Observed behaviour:** 
Refresh goes into infinite loop ofter returning to `Centers` screen

**Device and Android version:** 

* Device: Pixel 2 XL Emulator
* Android Version: API 27 Android O(Oreo) - 8.1.0

**Screenshots:** 

Rec

### PR DESCRIPTION
**Pull request by danishjamal104**
Fixes #1568 

**Screen Recording**

Screenshot 2020-11-19 at 5 10 13 PM

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by danishjamal104** [comment]
@robustTechie please review the changes

**Comment by robustTechie** [comment]
Can you update the screen recording as it got stuck when you close the Center tab?

**Comment by danishjamal104** [comment]
> Can you update the screen recording as it got stuck when you close the Center tab?

In my browser, it's showing fine can you please recheck it??

**Comment by danishjamal104** [comment]
@robustTechie I have updated the gif. Please take a look if its fine.

**Review by robustTechie — APPROVED** [review]

**Review by iamsh4shank — APPROVED** [review]

**Pull request merged**
