### PR TITLE
Hide Keyboard after pressing save button while creating new client in offline mode

### LINKED ISSUE #1403: hidden toaster message  while creating a new client in offline mode
**Summary:** 
toaster message is not visible after saving the data ,close the keyboard after clicked  on save data.

**Steps to reproduce:** 

menu bar<clients<Floating button (to add client)<enter the fields and submit<User fields <save

**Expected behaviour:** 

after saving the required data the keyboard get hides automatically,so that user can see the toast 
message.

**Observed behaviour:** 

after clicking on save the keyboard remain open and user cant see the toast message ,which get 
hides under the keyboard 

**Device and Android version:** 

Redmi 6
Android 9

**Screenshots:** 
ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by neeraj0403**
Fixes #1403 

UI changes

ezgif com-video-to-gif (5)

Please make sure these boxes are checked before submitting your pull request - thanks!

-  [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Grandolf49** [comment]
@neeraj0403 Please squash your commits :)
Also, since there are UI changes can you add Screenshots or GIFs?

**Comment by neeraj0403** [comment]
@Grandolf49 i have solved a new issue and in a new branch with only a single commit...so do i need to squash my commit ?

**Comment by robustTechie** [comment]
@neeraj0403  #1288 is the same issue and already a fix for that is sent in PR #1289. Please close the duplicate issue.

**Comment by neeraj0403** [comment]
@robustTechie bro this issue is under offline mode and the  updation of the code is also in another class i.e. DatatTablelistFragment.java

**Comment by AbhilashG97** [comment]
Hello @neeraj0403,

Can you please squash your commits?

I'm closing your pull request for now. Please re-open this pull request when you have made the suggested changes.

Thank you for your contribution.

**Pull request closed without merging**
