### PR TITLE
View conflicts in Create Group and Create Center.

### PR DESCRIPTION
**Pull request by yvsssantosh**

### CODE REVIEW

**Comment by yvsssantosh** [comment]
@ishan1604 Please review my code changes

Thank You

**Comment by ishan1604** [comment]
Please resolve the merge conflicts and send a new PR. 

Make sure squash your commits and add description about what this PR.

Thanks

**Comment by yvsssantosh** [comment]
@ishan1604 
The essence of this PR is that the Activation date is hiding the submission date instead in the app
So its better to have a separate activation date as we have in the web app of mifos


I'm having trouble with merging 
Kindly help me out

**Comment by yvsssantosh** [comment]
new PR created #231 

Kindly Review
@ishan1604 

Thank You

**Pull request closed without merging**
