### PR TITLE
Fixed snackbar text color

### LINKED ISSUE #1893: Snackbar text isn't visible
**Summary:** 

Snackbar text isn't visible 

**Steps to reproduce:** 

- open the app
- click on "Connection Settings"
- write "demo.mifos.community" instead of "demo.mifos.io"
- A snackbar appears with an invisible text or no text

**Expected behaviour:** 

Proper error message should be displayed in the snackbar

**Observed behaviour:** 

The error message isn't visible in the snackbar

**Device and Android version:** 

Device : Samsumg M11
Android: 11

**Screenshots:** 
WhatsApp Image 2023-02-06 at 02 07 09

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1893 

Screenshot_2023-02-23-15-28-54-53_3b69eb5d9a470d17be550edd2848b555

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
> Fixes #1893 
> 
> Screenshot_2023-02-23-15-28-54-53_3b69eb5d9a470d17be550edd2848b555
> 
> 
> Please make sure these boxes are checked before submitting your pull request - thanks!
> 
> - [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
> 
> - [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
> 
> - [x] If you have multiple commits please combine them into one commit by squashing them.

Did you checked for light mode as well?

**Comment by Aditya-gupta99** [comment]
@avinash14022002  Yes, it is working as expected.

**Comment by avinash14022002** [comment]
@Aditya-gupta99 ,
check why PMD is getting fail

**Comment by Aditya-gupta99** [comment]
I have opened another PR #1945.

**Pull request closed without merging**
