### PR TITLE
Fixes #1700: Legend added in ClientDetailsFragment

### LINKED ISSUE #1700: New Feature: Adding legends to Savings and Loans List in ClientDetails
**Summary:** 
When user open opens client details and if anyone of list is opened from loan, savings and recurring type there are different notations as colour against each items and usually there is legend that shows which colour indicates which type. So a layout should be added at top of each list that shows up when respective list is opened

**Expected behaviour:** 
Legend should be added

**Device and Android version:** 
Any

https://user-images.githubusercontent.com/70195106/103421396-1dc32900-4bc2-11eb-9170-a06c8d85451e.mp4

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1700 

https://user-images.githubusercontent.com/70195106/103423047-8e6e4380-4bca-11eb-9f21-4aac6f3aa0bf.mp4

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — CHANGES_REQUESTED** [review]
Don't you think we should use the chip for displaying legends since it is the material component and suggested by Google?  
It will also make code very small and increase readability. 
[Chips](https://material.io/components/chips/android#using-chips)

**Comment by PatelVatsalB21** [comment]
@danishjamal104 thanks for informing me about chips. I will try best to implement it :)

**Comment by danishjamal104** [comment]
> @danishjamal104 thanks for informing me about chips. I will try best to implement it :)

Any update?

**Comment by PatelVatsalB21** [comment]
> > @danishjamal104 thanks for informing me about chips. I will try best to implement it :)
> 
> Any update?

@danishjamal104 I will be less active as my college exams are declared to be near Feb starting. Still working on this issue. Don't worry as I said I will work on it. 😊

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Hey @PatelVatsalB21 can you fix the merge conflicts so that we could merge it soon :)

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
