### PR TITLE
Fixes #1570 : (Fixed) Swipe Refresh Layout is refreshing when pressed back button(twice) while creating groups

### LINKED ISSUE #1570: SwipeRefreshLayout goes into infinite loop in Groups section
**Summary:** 
In Groups section `swipeRefreshLayout` goes into infinite loop as it is not set to false when returned back to the Fragment.

**Steps to reproduce:** 
1. Navigate to `Groups` using the option in `Navigation Drawer`
2. After data is loaded click on `Plus FAB` in the bottom right.
3. Now press the back button twice to return back to `Groups Screen`
4. Observe the refresh icon on `Center-Top` of the screen.

**Expected behaviour:** 
* Possibility 1: No refresh should be triggered on returning back 
* Possibility 2: Refresh should be triggered and should stop once the data is loaded

**Observed behaviour:** 
SwipeRefreshLayout goes into infinite refresh ofter returning to `Groups` screen

**Device and Android version:** 

* Device: Pixel 2 XL Emulator
* Android Version: API 27 Android O(Oreo) - 8.1.0

**Screenshots:** 

Rec

### LINKED ISSUE #1800: Swipe Refresh Layout is refreshing when pressed back button(twice) while creating groups
**Summary:** 

When user tries to create a group and presses back button, the refresh layout is set to refreshing which should not be done when no new group is created.

**Steps to reproduce:** 

1) Go to Groups
2) Click on '+' button 
3) Press back button twice

**Expected behaviour:** 

https://user-images.githubusercontent.com/47531297/110196101-3f61ba80-7e68-11eb-9da5-dd0d821a2357.mp4

**Observed behaviour:** 

https://user-images.githubusercontent.com/47531297/110196125-6a4c0e80-7e68-11eb-8f11-af8da4309c62.mp4

**Device and Android version:** 
Any

### PR DESCRIPTION
**Pull request by sreyans01**
Fixes #1570 :
✓    Apply the MifosStyle.xml style template to your code in Android Studio.
✓    Run the unit tests with ./gradlew check to make sure you didn't break anything

✓    If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by sreyans01** [comment]
I would request the project mentors to please review and merge my pull request. If there's any issue, please drop a comment below.

**Recording after Fix:**

https://user-images.githubusercontent.com/47531297/110204632-13f7c380-7e9a-11eb-8880-efc02d5d123a.mp4

**Comment by danishjamal104** [comment]
why have you closed the PR @sreyans01 ?

**Comment by sreyans01** [comment]
> 
> 
> why have you closed the PR @sreyans01 ?

Sir, I was unable to figure out why is build test getting failed in github, thatswhy I closed the PR. It would be very nice if you could guide me out to make the tests pass in the build.

**Comment by sreyans01** [comment]
I closed it because the build was failing. Now, I have reopened it and
linked it to the correct issue #1570 , and all the checks have been passed.

**Comment by vinayak0505** [comment]
> > why have you closed the PR @sreyans01 ?
> 
> Sir, I was unable to figure out why is build test getting failed in github, thatswhy I closed the PR. It would be very nice if you could guide me out to make the tests pass in the build.

can you help me how you fixed that GitHub build because I am also facing the same issue, Thank You

**Comment by PatelVatsalB21** [comment]
@danishjamal104 is #1571 not relevant. If yes then this is repetitive pr. Isn't it?

**Comment by sreyans01** [comment]
> 
> 
> > > why have you closed the PR @sreyans01 ?
> > 
> > 
> > Sir, I was unable to figure out why is build test getting failed in github, thatswhy I closed the PR. It would be very nice if you could guide me out to make the tests pass in the build.
> 
> can you help me how you fixed that GitHub build because I am also facing the same issue, Thank You

I just did another unit test and made a new pull request.

**Comment by sreyans01** [comment]
> 
> 
> @danishjamal104 is #1571 not relevant. If yes then this is repetitive pr. Isn't it?

Its a repetitive pr of #1801 which was made and closed by me due to failed build tests. Now it got passed, so I created this one and closed the previous one.

**Review by PatelVatsalB21 — COMMENTED** [review]
@sreyans01 You can change code inside same pr by force pushing local commit instead of making new branch every time. It might help you manage prs ahead.

**Comment by sreyans01** [comment]
> 
> 
> @sreyans01 You can change code inside same pr by force pushing local commit instead of making new branch every time. It might help you manage prs ahead.

Yes, I will do that from next time.

**Pull request closed without merging**
