### PR TITLE
feat: Two-Factor Authentication Support

### PR DESCRIPTION
**Pull request by alexivanov**
This PR adds support for two-factor authentication.

Server-side implementation details are described [here](https://mifosforge.jira.com/wiki/spaces/projects/pages/185277689/GSoC+2017+-+Two-Factor+Authentication).

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@MegaAlex Thanks for contribution, 
This PR is not related to any issue so I am hoping a proper description in PR descriptions before the review.

Add these things 
1.  About the issue
2. What's your approach?

**Comment by MegaAlex** [comment]
@therajanmaurya Yes, sorry about that. I will provide better description.

**Comment by tarun0** [comment]
@alexivanov Can you resolve the conflicts? @edcable Please verify that the server side implementation is finished?

**Comment by droidchef** [comment]
Conflicts were not resolved by the author so I am closing this PR.

**Pull request closed without merging**
