### PR TITLE
Fixes #1779: Toast message in ClientDetailsFragment appears for a longer time

### LINKED ISSUE #1779: Toast message in ClientDetailsFragment
**Summary:** 

When changing the client picture, if you click any of take new photo or upload new photo and go back without clicking or uploading respectively, the toast message which appears disappears too fast

**Steps to reproduce:** 

Go to client list from side navigation -> Click on any client -> Click on client profile picture -> Choose either of teake new photo or upload new photo -> Go back without performing any action

**Expected behaviour:** 

Show the toast message for a while in order to be seen clearly

**Observed behaviour:** 

The toast message disappears too fast

**Device and Android version:** 

RedMi Note 8 Pro
Android 9

**Screenshots:** 

https://user-images.githubusercontent.com/52701183/108369377-8a04f500-7221-11eb-8f3f-866e1b122549.mp4

### PR DESCRIPTION
**Pull request by Abhinavtdk**
Fixes #1779 

https://user-images.githubusercontent.com/52701183/108375307-d6533380-7227-11eb-890e-9c3a542c1949.mp4

- [X] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Comment by PatelVatsalB21** [comment]
@Abhinavtdk you can keep branch name based on error eg - fix_#1779 rather than descriptive branch name.

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
