### PR TITLE
Correct text alignment of CheckBox in Create Client, Create Center and Create Group

### PR DESCRIPTION
**Pull request by prem0862**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@Prem0707 Please fix the PR Title and please follow the [commit guidelines](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide)

**Comment by Prem0707** [comment]
@luckyman20 what should be correct PR title, Please suggest. Thanks

**Comment by luckyman20** [comment]
@Prem0707 Correct Title - `Correct text alignment of CheckBox in Create Client, Create Center and Create Group`

**Comment by Prem0707** [comment]
Fixes #893

**Comment by luckyman20** [comment]
@Prem0707 Please follow the [commit guidelines](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide)

**Comment by Prem0707** [comment]
@luckyman I just changed changed commit message, Please take a look. Thanks

**Comment by luckyman20** [comment]
@Prem0707 Please change the commit message to `fix: Issue #893 - Correct text alignment of CheckBox in Create Client, Create Center and Create Group` and try to follow this pattern in all of yours PRs

**Comment by AbhilashG97** [comment]
Hello @prem0862, 

Can you please resolve the merge conflict and also fix the commit message?

I am closing this pull request for now. Please re-open this pull request when you have addressed the above-mentioned issues.

Thank you for your contribution. :sparkles:

**Pull request closed without merging**
