### PR TITLE
Fix Issue#848:Restricting user to move from passcode when offline

### PR DESCRIPTION
**Pull request by AkshGautam**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
Fix #848  
@therajanmaurya @tarun0  Please review.

**Comment by iml-v** [comment]
@AkshGautam  I think there is no need for this issue because user should able to enter into app even there is no available network  otherwise there will be no sense of offline mode in app  .

**Comment by iml-v** [comment]
Also  should discuss with  @therajanmaurya @tarun0  @luckyman20 .

**Comment by AkshGautam** [comment]
@iml-v  Thats a valid point. Did not think about that while creating the issue.

**Pull request closed without merging**
