### PR TITLE
fix: Completed DateHelper UnitTest

### LINKED ISSUE #1315: Adding more unit tests
**Scope of unit tests can be increased further** 

More unit tests should be added to make app more robust. Currently less than 10% of the app's code is under testing scope which should be increased.

### PR DESCRIPTION
**Pull request by pallav12**
Fixes #1315 
changes : Added null checks in DateHelper Class, added tests for remaining methods, asserted null in unit tests.

### CODE REVIEW

**Comment by Grandolf49** [comment]
Hey @pallav12. you are having a PMD violation in your PR. Please refer this file locally on your machine android-client/mifosng-android/build/reports/pmd/pmd.html.
This will tell you what the issue is exactly.

**Comment by Grandolf49** [comment]
@pallav12 Also, before sending the PR, please run the command `gradlew check` locally, from the android terminal. This will basically check your code for PMD violations and lot of other things.

**Comment by pallav12** [comment]
Thanks @Grandolf49, it worked. but gradlew check is still throwing error on local machine.

**Comment by Grandolf49** [comment]
@pallav12 what is the error?

**Comment by pallav12** [comment]
Screenshot (17)

There're 20 of these...
Screenshot (18)

**Comment by pallav12** [comment]
@luckyman20 @moksh-mahajan please review

**Pull request closed without merging**
