### PR TITLE
Update ClientDetailsFragment.java

### PR DESCRIPTION
**Pull request by top-gun007**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by top-gun007** [comment]
changes:downloading the image using glide instead of async task in the clientdetailsfragment

**Comment by therajanmaurya** [comment]
@top-gun007 you checkstyle is failing, you can find violate rules here android-client/mifosng-android/build/reports/checkstyle/checkstyle.html. 

To fix these rules, just open the ClientDetailsFragment and reformat the class and you are done.

**Comment by top-gun007** [comment]
thanks @therajanmaurya ....well I guess that's the difference between an expert and novice

**Comment by top-gun007** [comment]
thanks @therajanmaurya ....well I guess that's the difference between an expert and novice

**Pull request closed without merging**
