### PR TITLE
New Feature: Allow user to update server configuration

### PR DESCRIPTION
**Pull request by niyajali**
- [x] Created UpdateServerConfigScreen.kt
- [x] Created Validation Use Cases
- [x]  Saved Config in Preference Manager
- [x] Applied in :app, :auth module
- [x] Applied in Network Module

Fixes [MIFOSAC-167](https://mifosforge.jira.com/browse/MIFOSAC-167?atlOrigin=eyJpIjoiMjg3YzdjYjNjZTMwNDdhOTkwNmFlMzc2MWNiNmM2MzUiLCJwIjoiaiJ9)

Please Add Screenshots If there are any UI changes.

https://github.com/openMF/android-client/assets/26448068/4693da70-2640-441e-85af-708b1ee639d1

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

[MIFOSAC-167]: https://mifosforge.jira.com/browse/MIFOSAC-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by niyajali** [comment]
@therajanmaurya kindly review this PR, I haven't applied in :network module yet,  this is the main internal part like the heart of our app, so I would like to discuss it with you before using it in the module, it will be better if we could join a meeting with @Aditya-gupta99 to share my thoughts properly.

**Comment by therajanmaurya** [comment]
This does not need to interact with network module. It will interact with data - datastore module 
datastore - It will have function to update the config 
data - It will expose the datastore update config function. We already have the functions 
image

**Comment by niyajali** [comment]
yes sir but i think we have to configure BaseApiManager as well because in their we are using prefManager

**Comment by niyajali** [comment]
@therajanmaurya sir applied config in network module, kindly take a look

**Pull request merged**
