### PR TITLE
Added new feature of Initial letter based bitmap for circular image view

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
New Feature #1591 Initial letter of User or Client is printed and changes background color randomly from selected value of colorset every time object is created. This is done with help of  [Avatar Image Generator ](https://github.com/AmosKorir/AvatarImageGenerator) repo whose dependency i have added in build.gradle .

Screenshot_20201203-153036
Screenshot_20201203-153329
Screenshot_20201203-153343

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — APPROVED** [review]
Nice work @PatelVatsalB21 , LGTM

**Comment by PatelVatsalB21** [comment]
Thank you 😊

**Review by robustTechie — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
