### PR TITLE
Fixes #1754 : Last item not selecting in NewIndividualCollectionSheetFragment fixed

### LINKED ISSUE #1754: Last item in offices and staff spinner not selecting in NewIndividualCollectionSheetFragment
**Summary:** 

Last item in offices and staff spinner not selecting in NewIndividualCollectionSheetFragment.
As shown in video attached it says select an office even on selecting last item in office spinner and select a staff on selecting last item in staff spinner.

**Steps to reproduce:** 

1. Select Individual collection Fragment from Navigation Drawer.
2. Select the last item in office spinner or in staff spinner.

**Expected behaviour:** 

It must treat them as others in the list and treat it as selected.

**Observed behaviour:** 

It says please select as if nothing is selected.

**Device and Android version:** 

Any

https://user-images.githubusercontent.com/67901968/107176955-a53c5d00-69f6-11eb-8c2b-0c2cb72b9c4a.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1754 

https://user-images.githubusercontent.com/67901968/107177215-4d522600-69f7-11eb-939d-d8ab4de52e2a.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by robustTechie — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
