### PR TITLE
Added functionality to upload existing photo in Edit client page

### LINKED ISSUE #1182: No options to upload existing photo in Edit client page.
1) Go to left navigation page and tap on Clients.
 2) In clients list page, click on '+' icon.
 3) In next create client page, tap on image and then select take photo.
 4) Submit client with other mandatory fields.
5) Go to the client page, and tap on the image.
Expected: It should show both 'Take photo' and Upload Photo options.
Actual: Its only showing take photo option. Uploading existing photo is not  available.

### PR DESCRIPTION
**Pull request by Vanshika-Mittal**
Fixes #1182: No options to upload existing photo in Edit client page

[Task link](https://codein.withgoogle.com/dashboard/task-instances/4725971010191360/)

screen-recorder

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [x]  If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by moksh-mahajan** [comment]
@Vanshika-Mittal 
1) Please follow the default template for sending PRs. Check out other PRs.
2) Add screenshots/gifs in case of UI changes.

**Comment by Vanshika-Mittal** [comment]
@moksh-mahajan 
I have made the required changes. Please review my PR now.

**Comment by moksh-mahajan** [comment]
@Vanshika-Mittal You have not added the code to upload the client image (chosen from gallery/storage) to the server. You are just setting the image to the CircularImageView. Please look into this.

**Comment by jsahil730** [comment]
@luckyman20 can you close this PR? The student missed the deadline for this task.

**Comment by laxyapahuja** [comment]
I think this PR can be closed now. @luckyman20

**Pull request closed without merging**
