### PR TITLE
#Fixed MIFOSAC -122 / Re-login after using wrong tenant ID.

### PR DESCRIPTION
**Pull request by Vatsal-Bajpai**

### CODE REVIEW

**Comment by fomenkoo** [comment]
Wrong kind of fix - this way you erase all the settings, including server url and other.

**Comment by Vatsal-Bajpai** [comment]
@fomenkoo Thank you for your review and sorry for making a wrong fix. I have updated the code. The issue was the TenantId was being stored in prefs after successful login but to login it self at the first place the TenantId was being read from prefs, so i just saved TenantId before login.

**Comment by fomenkoo** [comment]
@Vatsal-Bajpai 
Also, please squash your commits - that will help Ishan to merge and review your PR faster :) 

You can find on how to use squash in this article: 
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Or just simply you can reset your branch with:
git reset HEAD~n, where n - the number of the commits you want to merge.

**Comment by Vatsal-Bajpai** [comment]
@fomenkoo 
Thank you for your suggestion, i have rebased both the commits to one.
@ishan1604 
Please review the PR now.

**Comment by ishan1604** [comment]
@Vatsal-Bajpai I still see two commits here.

**Pull request closed without merging**
