### PR TITLE
Replaced TextView with Button for Connection Settings

### PR DESCRIPTION
**Pull request by Pritom14**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by devkhan** [comment]
This seems good. Now please close the other two PRs. And it'd be nice to post some screenshot of the changes you've made.

@therajanmaurya Will further review this.

**Comment by Pritom14** [comment]
I will surely post the screenshots @devkhan

**Comment by Pritom14** [comment]
issue1

**Comment by therajanmaurya** [comment]
@Pritom14 I do not like the UI that you have made. Please make the UI like #544

**Comment by therajanmaurya** [comment]
fixed in #552

**Pull request closed without merging**
