### PR TITLE
Fix : Back Button not working when sync surveys dialog opens in settings tab #1142

### LINKED ISSUE #1142: Back Button not working when sync surveys dialog opens in settings tab
**Summary:** 
Back Button not working when sync surveys dialog is opened on pressing sync surveys in settings tab available in navigation drawer .The desired functionality must be that Background area should not be functional (on pressing) but back button must work and dialog should get dismissed on pressing back.

**Steps to reproduce:** 
1. Open Navigation Drawer.
2. Click on settings.
3. Toggle on the sync surveys button.
4. Sync Surveys dialog will appear.
5. Click on back and nothing will happen

**Expected behaviour:** 
The desired functionality must be that Background area should not be functional (on pressing) but back button must work and dialog should get dismissed on pressing back.

**Observed behaviour:** 
Back Button not working when sync surveys dialog is opened on pressing sync surveys in settings tab available in navigation drawer

**Device and Android version:** 

Same behaviour on all devices but screenshot attached of Moto E (Android 5.1)

**Screenshots:** 
Screenshot_2019-03-17-14-33-06

### PR DESCRIPTION
**Pull request by RashulChutani**
Fixes #1142

### CODE REVIEW

**Comment by luckyman20** [comment]
@RashulChutani Please fix the travis error and squash the commits.

**Comment by RashulChutani** [comment]
Sir Please help me resolve the travis error as I have modified only one file named "SyncSurveysDialogFragment" and no changes of Gradle files have been pushed. Kindly help

**Comment by apoorva-mk** [comment]
@RashulChutani I looked through the log and it looks like your code didn't adhere to the style guidelines and hence the travis build failed.

**Comment by RashulChutani** [comment]
@apoorva-mk Please Can you send me the link to follow the style conventions It would be of great help.

**Comment by apoorva-mk** [comment]
@RashulChutani https://github.com/openMF/mobile-wallet/blob/master/.github/CONTRIBUTING.md
Look through the Pull requests guidelines section

**Comment by RashulChutani** [comment]
@luckyman20 @apoorva-mk I have solved the Travis error and squashed the commits.Kindly review

**Comment by RashulChutani** [comment]
@droidchef  I have solved the Travis error and squashed the commits.Kindly review

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the java file has now been migrated to kotlin

**Pull request closed without merging**
