### PR TITLE
Fixes #1854 Search, Notes and staff data manager converted to kotlin

### LINKED ISSUE #1854: Convert data managers source code language to Kotlin
**Summary:** 

This issue focuses on converting the DataManager classes to Kotlin. Since their is ongoing migration of APIs to SDK, it would be easier to convert the language to Kotlin too.
Their will be multiple PRs referring this issue.

### PR DESCRIPTION
**Pull request by danishjamal104**
Fixes #1854 

Search data manager is not migrated to Kotlin, due to `SearchPresenterTest` failure. The reason for the failure of test is because mockito version 1 was not capable of mocking closed classes and in Kotlin by default all classes are closed. This issue will be resolved in subsequent PR.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by danishjamal104** [comment]
@iamsh4shank, @Grandolf49, @luckyman20   please review and merge this. Thanks

**Comment by luckyman20** [comment]
@danishjamal104 I am not in touch with this project so I won't be able to review it.

**Comment by danishjamal104** [comment]
> @danishjamal104 I am not in touch with this project so I won't be able to review it.
> 
> Also, your build is failing so you might be interested in taking a look at that.

the build is failing because, it is not able to GET pad/checkstyle dependency, which is causing most of the checks to fail. @iamsh4shank must be aware about it.

**Comment by iamsh4shank** [comment]
> > @danishjamal104 I am not in touch with this project so I won't be able to review it.
> > Also, your build is failing so you might be interested in taking a look at that.
> 
> the build is failing because, it is not able to GET pad/checkstyle dependency, which is causing most of the checks to fail. @iamsh4shank must be aware about it.

Yeah there is some issue with PMD plugin

**Comment by Aditya-gupta99** [comment]
We're closing this PR since it's already fixed

**Pull request closed without merging**
