### PR TITLE
UI changes

### LINKED ISSUE #1024: UI improvements in the Dashboard.
**Summary:** 

The Dashboard activity looks clumsy when an option from the search filter is chosen.
The Search filter drop down (Spinner) is too near to the Search TextView, which makes it look clumsy when an option is chosen.
And also the view isn't proportionate.
Thus the UI can be enhanced.

**Steps to reproduce:** 

Open the app. The Search Dashboard appears.

**Device and Android version:** 

Redmi Note 4 (Mido)
Nougat 7.0

**Screenshots:**

### PR DESCRIPTION
**Pull request by theamritanair**
Fixes #1024 

**After the change:**

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by theamritanair** [comment]
@therajanmaurya please review this.

**Comment by theamritanair** [comment]
@droidchef please review this PR.

**Comment by droidchef** [comment]
Thank you for the fix. Could you please change the commit message to be a bit more meaningful.

Looking at a commit message saying UI changes, doesn't tell the reader anything.

**Comment by theamritanair** [comment]
@droidchef I've changed the commit message. Can you please review this?

**Comment by droidchef** [comment]
@theamritanair The commit message now says

"Fix: Improvement in the UI of the Dashboard"

A commit either fixes something or improves something. If it does multiple things they should be split into multiple commits.

Now, Improvement in the UI of the dashboard. What did you improve? Why did you improve that?

Can you please write it in the commit message?

**Comment by Aditya-gupta99** [comment]
Closing this PR since the XML file has been updated

**Pull request closed without merging**
