### PR TITLE
Fixes #1714: Done key is also made to search in Dashboard Activity 

### LINKED ISSUE #1714: New small update: Done or enter key on app keyboard can also be made to search
**Summary:** 

Done or enter key on app keyboard can also be made to search in dashboard activity.
Since many of us press that before search button when we have finished writing.

**Expected behaviour:** 

Automatically search starts on pressing done without pressing search button.

**Observed behaviour:** 

It doesn' t happen previously.

**Device and Android version:** 

Any

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1714 

Please Add Screenshots If there are any UI changes.
https://user-images.githubusercontent.com/67901968/104809994-c5259a00-5817-11eb-98ee-02a1a979c013.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 here also pr number is not necessary like previous one . Please change it. Also go through other prs and check commit message, heading and details format of pr. That will help you. Thank you.

**Review by PatelVatsalB21 — COMMENTED** [review]
@NikunjGarg2000 here also pr number is not necessary like previous one . Please change it. Also go through other prs and check commit message, heading and details format of pr. That will help you. Thank you.

**Comment by NikunjGarg2000** [comment]
Ok @PatelVatsalB21, I will.
Thank You.

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
I have opened another PR #1954

**Pull request closed without merging**
