### PR TITLE
Integrated NDK and Pass Code Feature

### PR DESCRIPTION
**Pull request by mayank-kgp**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.
#697 and #698

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@therajanmaurya @puneetkohli521 Please review it.
demo3

**Comment by droidchef** [comment]
I suggest we clear ```Preferences``` related to pass code authentication when app is killed or after it stays in the background for X minutes and user returns.

**Comment by mayank-kgp** [comment]
@dilpreet96 Please see Ishan's suggestion.

**Comment by dilpreet96** [comment]
@droidchef Are suggesting to show the passcode screen when he comes back to the application from app in background and when we turns on the screen after it was turned off ?

**Comment by droidchef** [comment]
@dilpreet96 Precisely yes! 

For coming back from Background have a min threshold time, lets say 2 minutes or so because imagine I am using the app and suddenly get a call or have to answer someone on whatsapp, if I return back from there in a minute or 2 I shouldn't have to add the passcode, but if I am out for a time longer than that, you should ask me for my passcode.

**Comment by dilpreet96** [comment]
Thanks for the clarification @droidchef , will be updating the PR soon.

**Comment by therajanmaurya** [comment]
@mayank-kgp Please add screen shots

**Comment by mayank-kgp** [comment]
@therajanmaurya @puneetkohli521 I have updated the GIF. For demo purpose, I have used 5 seconds for showing the passcode screen again if the app is in background. I am keeping 120 seconds in actual implementation as Ishan suggested.

**Pull request merged**
