### PR TITLE
Changed the snack bar timer length from Indefinite to Long in Login Activity

### LINKED ISSUE #1359: Indefinite length time of snack bars in Login Activity
**Summary:** 

The Snack bars which are occurring in Login Activity have an indefinite length which shows the Snackbar indefinitely.

**Steps to reproduce:** 

Go to Login Activity and try to login with empty or incorrect credentials. You will see the Snack bars at the bottom.

**Expected behaviour:** 

The Snack bars should have either a short period of time or a long period of time but not Indefinite.

**Observed behaviour:** 

The Snack bars are having Indefinite length time.

**Device and Android version:** 

Device: RedMi Note 8 Pro
Android Version: 9

**Screenshots:** 

Screenshot_2020-02-29-18-03-31-337_com mifos mifosxdroid 1

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #1359

Now the snack bar is disappearing after a specific time.
**GIF:**

ezgif com-video-to-gif

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing the.

### CODE REVIEW

**Comment by robustTechie** [comment]
Add the screenshot also so that the reviewer can see the changes you made.

**Comment by RajaVamsi11** [comment]
@robustTechie Done.

**Comment by robustTechie** [comment]
Great

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved

**Pull request closed without merging**
