### PR TITLE
Fix: allow client name less than 4 characters

### PR DESCRIPTION
**Pull request by mayank-kgp**
Resolves issue #746

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@droidchef @therajanmaurya Please review this.

**Comment by droidchef** [comment]
You removed the validation completely ? Why ?

**Comment by therajanmaurya** [comment]
@mayank-kgp can you please follow the @droidchef comment.

**Comment by therajanmaurya** [comment]
Ohh Sorry, my bad, @droidchef Please accept the changes and merge.

**Pull request merged**
