### PR TITLE
Deleted all unused import statements

### LINKED ISSUE #1350: Delete unused import statements
**Summary:** 

After analyzing the project I found that there are some unused import statements on `SettingsFragment.java`. My idea is to remove those unused import statements to make code look cleaner.

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #1350 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@tarun0 @moksh-mahajan Can you please review it?

**Comment by robustTechie** [comment]
@RajaVamsi11 are you sure every import statement is removed?

**Comment by RajaVamsi11** [comment]
Yes

**Comment by AbhilashG97** [comment]
Hello @RajaVamsi11, 

Can you please correct your commit message so that it can be merged? Please refer to the [wiki page](https://github.com/openMF/android-client/wiki) to know more about the commit style used in this project.

**Pull request merged**
