### PR TITLE
Fix 561: SwipeRefreshLayout keeps refreshing

### LINKED ISSUE #561: SwipeRefreshLayout keeps on refreshing
**Summary:** 

The SwipeRefreshLayout on Group List and Client List keeps on refreshing on coming back from `Create Client/Group` screen.

**Steps to reproduce:** 

Open `Clients` from the navigation drawer. Click on the *+* floating action button. Press back button

**Expected behavior:** 

Only the list should have been shown.

**Observed behavior:** 

The list is shown but the refreshing view is still there.

**Device and Android version:** 

Android Emulator - API 23

**Screenshots:** 

refresh

### PR DESCRIPTION
**Pull request by tarun0**
Fix #561 

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@tarun0 Inject the View ` ((MifosBaseActivity) getActivity()).getActivityComponent().inject(this);` in 
`public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle`
Everthing will work fine.
Make the change and Let me know.

**Comment by tarun0** [comment]
@therajanmaurya The view was already injected (the statement is there in both the files) but the issue still persisted.
The PR does address the issue, though.

**Comment by therajanmaurya** [comment]
@tarun0 I have tested that putting this line `((MifosBaseActivity) getActivity()).getActivityComponent().inject(this);` in `public View onCreateView(..)` solving the problem.

**Comment by tarun0** [comment]
@therajanmaurya I did what you suggested. It did remove the refreshing but did not show the (client) list before manually refreshing. Please let me know if I need to do something else as well. 

refresh

**Comment by therajanmaurya** [comment]
@tarun0 Fix the conflicts

**Comment by droidchef** [comment]
This PR needs conflict resolution.

**Pull request closed without merging**
