### PR TITLE
No activation date in Create Center and Create Group

### PR DESCRIPTION
**Pull request by yvsssantosh**
Fixes

* - As in the web application there is no Activation Date in the Create Group and Create Center

Kindly Review
@ishan1604

### CODE REVIEW

**Comment by nellyk** [comment]
Hi @yvsssantosh  i really like how you implemented this , would you like me to assign you something similar to this on the create client functionality , https://mifosforge.jira.com/projects/MIFOSAC/issues/MIFOSAC-124?filter=allopenissues have a look and inform me if you would like to work on this. Thank you

**Comment by ishan1604** [comment]
https://github.com/openMF/android-client/wiki/Pull-Requests-FAQ

**Comment by yvsssantosh** [comment]
@nellyk 
Sure thing! I'd love to work on it :)

**Comment by nellyk** [comment]
Hi @yvsssantosh  sorry the issue was resolved with this pull request (https://github.com/openMF/android-client/pull/239) , you can pick another issue from Jira

Thank you

**Pull request closed without merging**
