### PR TITLE
ImageLoadingAsyncTask to Picasso, for image loading in different thread.

### PR DESCRIPTION
**Pull request by therajanmaurya**
PR #207  squashed . @ishan1604 Please review and merge.

### CODE REVIEW

**Comment by fomenkoo** [comment]
Great PR, thanks! 

1. Please, follow formatting guides for java. 
[don't use C# conventions](https://github.com/therajanmaurya/android-client/blob/b372cc0a937187e94a8a7b1fc340bf9700b3608a/mifosng-android/src/main/java/com/mifos/api/OauthOkHttpClient.java)

2. Don't hardcode tenant identifier, it should be used from PrefManager. 
> .addHeader(ApiRequestInterceptor.HEADER_TENANT, "default")

3. Please add this header to all new classes. 
/*
 * This project is licensed under the open source MPL V2.
 * See https://github.com/openMF/android-client/blob/master/LICENSE.md
 */

4. Remove empty override implementations in your code:
http://prntscr.com/afd9cq

Well done!

**Comment by therajanmaurya** [comment]
@fomenkoo thanks,

Please review #223 , I followed your point and these are fixed now.

Thanks.

**Comment by fomenkoo** [comment]
You haven't changed your formatting for your files (brace): 

https://github.com/therajanmaurya/android-client/blob/b372cc0a937187e94a8a7b1fc340bf9700b3608a/mifosng-android/src/main/java/com/mifos/api/OauthOkHttpClient.java

Take a look to this sample:

https://github.com/therajanmaurya/android-client/blob/b372cc0a937187e94a8a7b1fc340bf9700b3608a/mifosng-android/src/main/java/com/mifos/api/ApiEndpoint.java

**Comment by therajanmaurya** [comment]
Yes I have done the file formatting https://github.com/therajanmaurya/android-client/commit/bb0dfc86521fb7395bf48cdebe88678d65e24fd7
 Please check.

**Comment by therajanmaurya** [comment]
ImageLoadingAsyncTask to Picasso, for image loading in different thread.

squashed Please Review @ishan1604

**Pull request closed without merging**
