### PR TITLE
fixes #1722 : Lag in seeing clients in GroupDetailsFragment fixed

### LINKED ISSUE #1722: Lag in seeing Group clients in GroupDetailsFragment
**Summary:** 

Lag in seeing Group clients in GroupDetailsFragment
While seeing clients previous screen appears in between.

**Steps to reproduce:** 

1. Go to groups from Navigation drawer.
2. Open any group and select Group clients from its menu.
3. The clients screen is visible and while loading it previous group details screen appears.

**Expected behaviour:** 

After clicking for clients, group detail screen shouldn't appear in between.

**Observed behaviour:** 

After clicking for clients, group detail screen appears in between the loading for clients.

**Device and Android version:** 

REALME X
ANDROID 10

https://user-images.githubusercontent.com/67901968/104897459-68a0b700-599e-11eb-995b-5bb996eaf8b5.mp4

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1722 

https://user-images.githubusercontent.com/67901968/105323856-ab59cd80-5bf0-11eb-8f3c-d5afe8c6bed9.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — COMMENTED** [review]
@NikunjGarg2000 i can still see group details during transition to client list in pr video.

**Comment by NikunjGarg2000** [comment]
Sorry I attached wrong pr video, I have updated. Please check @PatelVatsalB21 .
Thank you.

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by danishjamal104 — APPROVED** [review]
LGTM

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
