### PR TITLE
Fixed issue #434

### PR DESCRIPTION
**Pull request by jainkuniya**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

mifos solved issue 434

### CODE REVIEW

**Comment by vishwesh3** [comment]
@therajanmaurya  @tarun0 Please have a look when you get some time.

**Comment by therajanmaurya** [comment]
@vishwesh3 Looks Good
@ishan1604 Give a final Review

**Comment by therajanmaurya** [comment]
@vishwesh3 Can you please fix this PR.

**Comment by luckyman20** [comment]
@jainkuniya Please resolve the conflicts

**Comment by jainkuniya** [comment]
@luckyman20 Done!

**Comment by luckyman20** [comment]
@jainkuniya Please squash the commits

**Comment by AkshGautam** [comment]
@therajanmaurya  since this PR did not resolve the conflicts hence #978  solves it.

**Pull request merged**
