### PR TITLE
[Enhancement] Cancelling app exit Toast on App exit

### LINKED ISSUE #1454: App 'Press again to exit Toast' issue
**Summary:** 

The toast doesn't disappear immediately even after the app closes.

**Steps to reproduce:** 

Just try exiting from the dashboard. The toast persists for a few seconds even after the app exits

**Expected behaviour:** 

The toast should get cancelled when app is closed

**Observed behaviour:** 

 The 'Press again to exit' toast persists for a few seconds even after the app exits

**Device and Android version:** 

I ran it on Nokia 3.1 plus running android API 28 (Android Pie)

**Screenshots:** 

I have screen record.. I'll post them on request if you still don't understand

### PR DESCRIPTION
**Pull request by shambu2k**
Fixes #1454 

Please make sure these boxes are checked before submitting your pull request - thanks!

[x] Apply the MifosStyle.xml style template to your code in Android Studio.

[x] Run the unit tests with ./gradlew check to make sure you didn't break anything

[x] If you have multiple commits please combine them into one commit by squashing them.

Before fix (the issue):

ezgif com-video-to-gif

After fix:

ezgif com-video-to-gif (1)

It may not be noticeable considerably through gifs. But while actually running them you can see the difference very well.

### CODE REVIEW

**Comment by Grandolf49** [comment]
hi @shambu2k While working on UI modifications, add screenshots or gifs of the changes so that they can be reviewed right away

**Comment by shambu2k** [comment]
I have a screen record.. I'll add that in half an hour, sorry..

**Comment by shambu2k** [comment]
> hi @shambu2k While working on UI modifications, add screenshots or gifs of the changes so that they can be reviewed right away

I have added it

**Comment by Aditya-gupta99** [comment]
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

**Pull request closed without merging**
