### PR TITLE
Loadmore ClientList and Refresh the ClientList fix.

### PR DESCRIPTION
**Pull request by therajanmaurya**
There was not Refresh functionality properly enable and LoadMore was not properly working.

Now it is fixed and officers can Refresh the Client List and view the Next Pagination Client List using scrolling down the list. 

@fomenkoo Please Review 
Thanks.

### CODE REVIEW

**Comment by fomenkoo** [comment]
Hi Rajan,

Good implementation - nothing to say more :)
Thanks to contributing! :)

@ishan1604 can you close this request?

**Comment by therajanmaurya** [comment]
Please Also look #223 

Thanks.

**Comment by ishan1604** [comment]
@therajanmaurya  :+1: for the implementation.

Here is my review of your code.

I think we can stick to naming the variables like this 
```
private boolean clientAvailable = true;
```

and not like this

```
private boolean ClientAvailable = true;
```

I also feel it would be great to call this variable `areMoreClientsAvailable` 

And since `CHECK_MORE_CLIENT` is not a constant it doesn't have to be named this way. 

only `static final` variables must be named like this. 

and since we are not writing our code in C we can try to refrain ourselves from using `1` & `0` Flags and use `boolean` instead. 

so you can modify the variable to ``` boolean shouldCheckForMoreClients```

Also please **squash** your commits when submitting PRs for a particular feature or bug fix.

**Comment by therajanmaurya** [comment]
Thanks @ishan1604,

I have changed variable names and squash. it's look good.
Please Review.

**Comment by ishan1604** [comment]
Looks good! Thanks

**Pull request merged**
