### PR TITLE
Fixes #1762 : UI enhancement done in item_checker_task.xml

### LINKED ISSUE #1762: UI Enhancement required in item_checker_task.xml
**Summary:** 

UI Enhancement required in item_checker_task.xml

**Steps to reproduce:** 

1. Open Navigation Drawer and choose Checker Inbox.
2. Choose checker inbox.

Observed Behaviour 
tv_checker_task_entity (ProvisionalEntities) overlapping cb_checker_task (checker box)

**Device and Android version:** 

Any

### PR DESCRIPTION
**Pull request by NikunjGarg2000**
Fixes #1762 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — CHANGES_REQUESTED** [review]
Text in next line visible at center doesn't look good. I think better is to set text gravity to `start|left`.

**Comment by NikunjGarg2000** [comment]
> Text in next line visible at center doesn't look good. I think better is to set text gravity to `start|left`.

image

@PatelVatsalB21 , that is not making any change and will not make since there is no space left to the right so no change of gravity. Also it is a demo and while user will make its use he must give space between two words so that will automatically come to next line.

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 i got it but this solution isn't looking pleasant. So can you suggest any change that can be made it layout to suit better?

**Comment by NikunjGarg2000** [comment]
Yes @PatelVatsalB21 , I too think it doesn't looks good but I can't really think of anything we can really do if user don't give spaces between words otherwise I might have done it. Let me think again and please suggest me something if you get what to be done.

**Comment by NikunjGarg2000** [comment]
@robustTechie please suggest something better possible for this.

**Comment by danishjamal104** [comment]
@NikunjGarg2000 , try using the below code snippet what it does is auto resizes the text to fit within bound try this and tell if it looks good.
```xml
<?xml version="1.0" encoding="utf-8"?>
<TextView
    android:layout_width="match_parent"
    android:layout_height="200dp"
    android:autoSizeTextType="uniform"
    android:autoSizeMinTextSize="12sp"
    android:autoSizeMaxTextSize="100sp"
    android:autoSizeStepGranularity="2sp" />
```

**Comment by NikunjGarg2000** [comment]
> @NikunjGarg2000 , try using the below code snippet what it does is auto resizes the text to fit within bound try this and tell if it looks good.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <TextView
>     android:layout_width="match_parent"
>     android:layout_height="200dp"
>     android:autoSizeTextType="uniform"
>     android:autoSizeMinTextSize="12sp"
>     android:autoSizeMaxTextSize="100sp"
>     android:autoSizeStepGranularity="2sp" />
> ```

@danishjamal104 great suggestion it is doing the work here for the word "ProvisionalEntries" but then the point comes to that the word can be bigger too if user don't give spaces.
image

**Pull request closed without merging**
