### PR TITLE
restructured: xml files for regex row*.xml and util files

### LINKED ISSUE #1867: Warnings on xml files for row regex and utils xml
**Summary:** 
Warnings on xmls files for row regex and utils xml

**Steps to reproduce:** 
By adding respective tags assignments

**Observed behaviour:** 
Removed warnings from XMLs

### PR DESCRIPTION
**Pull request by avinash14022002**
Fixes #1867 
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by avinash14022002** [comment]
Review and merge the code of this issue [Bintray ](https://github.com/openMF/android-client/issues/1864#issue-1173179754) then merge above code.

**Review by danishjamal104 — COMMENTED** [review]
Are you sure these changes won't break any UI?

**Comment by avinash14022002** [comment]
> Are you sure these changes won't break any UI?
@danishjamal104 
No UI break detected

**Review by danishjamal104 — APPROVED** [review]
LOOKS GOOD

**Pull request merged**
