### PR TITLE
Fix #1698: UI changes applied to ChargeDialogFragment

### LINKED ISSUE #1698: UI enhancements required in ChargeDialogFragment
**Summary:** 
Edittexts have grey background that does not looks good and colour of save button does not match with theme colour. Also dialog does not have heading

**Steps to reproduce:** 
1 Open Client Details
2 Open Charges from menu
3 Tap on + symbol

**Expected behaviour:** 
Editexts should be in transparent or white background. Also heading should be added and button color should be changed

**Device and Android version:** 
Lenovo Tab 7
Android 7

**Screenshots:** 
ss

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1698 

ss

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by danishjamal104 — CHANGES_REQUESTED** [review]
Increasing left/start padding in rows would make it look better, what do you say @PatelVatsalB21 ?

**Comment by PatelVatsalB21** [comment]
Sure @danishjamal104 I make changes soon

**Comment by PatelVatsalB21** [comment]
@danishjamal104 please review changes and newly updated image

**Comment by NikunjGarg2000** [comment]
I think increasing size a bit of heading i.e., create charge would make it look even more better, what's your say @PatelVatsalB21 ?

**Comment by PatelVatsalB21** [comment]
@NikunjGarg2000 I think it's good to keep fixed heading size in every dialog of app. That's why I didn't changed it.

**Comment by NikunjGarg2000** [comment]
Oh yes! that's good then @PatelVatsalB21

**Comment by Aditya-gupta99** [comment]
Closing this PR since the XML file has been updated

**Pull request closed without merging**
