### PR TITLE
fix: path tracker doesn't crash

### LINKED ISSUE #1165: App crashes on clicking path tracker
**Summary:** 

When trying to run path tracker service, the app just crashes throwing null pointer exception.

**Steps to reproduce:** 

From Dashboard, just click Path Tracker

**Expected behavior:** 

The app should show the tracked paths and allow the user to track his path.

**Observed behavior:** 

App crash.

**Device and Android version:** 

Device: Samsung and 6.1.0

### PR DESCRIPTION
**Pull request by laxyapahuja**
Fixes #1165 

ezgif-4-688a6b887840

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
@elirehema @moksh-mahajan can you please review this task? :D

**Comment by moksh-mahajan** [comment]
@laxyapahuja Please add a proper commit message explaining in brief how your changes fixed it.

**Comment by laxyapahuja** [comment]
@moksh-mahajan i've added a message. kindly check :D

**Comment by moksh-mahajan** [comment]
@laxyapahuja Please mention the exception type in the catch (like ArrayIndexOutOfBoundsException in this case) to make the code debuggable.

**Comment by laxyapahuja** [comment]
> @laxyapahuja Please mention the exception type in the catch (like ArrayIndexOutOfBoundsException in this case) to make the code debuggable.

@moksh-mahajan done :D

**Comment by moksh-mahajan** [comment]
LGTM. Good Job @laxyapahuja :)

**Comment by laxyapahuja** [comment]
> LGTM. Good Job @laxyapahuja :)

Thanks @moksh-mahajan. Can you approve this task on my dashboard?

**Comment by Aditya-gupta99** [comment]
The issue has already been resolved

**Pull request closed without merging**
