### PR TITLE
Fix 475: Incorrect content in client screen, if data is not available

### PR DESCRIPTION
**Pull request by mayank-kgp**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@therajanmaurya Please have a look at it :)

incclient

**Comment by therajanmaurya** [comment]
@mayank-kgp  Can you please fix this.

**Comment by mayank-kgp** [comment]
@therajanmaurya I will do it by evening :)

**Comment by mayank-kgp** [comment]
@therajanmaurya I am closing this PR and opening a new one - https://github.com/openMF/android-client/pull/555

**Comment by mayank-kgp** [comment]
@therajanmaurya I am closing this PR and opening a new one - #555

**Pull request closed without merging**
