### PR TITLE
Fixes #1643 empty screen fixed in individual collection sheet

### LINKED ISSUE #1643: Empty screen on returning back to Individual Collection Sheet
**Summary:** 

When we return back to the individual collection then an empty white screen is displayed.

**Steps to reproduce:** 

1. Go to the individual collection sheet page by navigating through the drawer.
2. Select office and loan officer and click `Generate`.
3. Now click `Fill Now`from the popup.
4. Finally Press the back button.

**Expected behaviour:** 

Proper UI must be shown.

**Observed behaviour:** 

Empty screen

**Device and Android version:** 

* GIONEE S6
* android M - 6.0

**Screenshots:** 

rec

### PR DESCRIPTION
**Pull request by danishjamal104**
Fixes #1643 

rec

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
hey @danishjamal104 can we also have previously user selected office on backpress to new Individual collection sheet.

**Comment by PatelVatsalB21** [comment]
@danishjamal104 can you please update pr name with issue number :)

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Can you fix the merge conflict

**Comment by iamsh4shank** [comment]
@danishjamal104 any updates on this?

**Comment by danishjamal104** [comment]
> @danishjamal104 any updates on this?

Will be done before evening

**Review by iamsh4shank — CHANGES_REQUESTED** [review]
Hey, @danishjamal104 can you fix the merge conflicts so that we could merge this soon :)

**Pull request merged**
