### PR TITLE
refactor: Sync Surveys Dialog Compose

### LINKED ISSUE #2161: refactor : Sync Surveys Dialog Compose
**Summary:** 

refactor : Sync Surveys Dialog Compose

**Select Type:**

- [x] UI Improvements
- [x] UI Add On
- [x] Improve Existing Code
- [x] New Feature
- [ ] Other

### PR DESCRIPTION
**Pull request by akashmeruva9**
Fixes #2161
Jira Task : [link](https://mifosforge.jira.com/browse/MIFOSAC-230)

<table style="border: 1px solid black;">
            <tr>
                <td  style="border: 1px solid black ;">
                    
                </td>
</table>

https://github.com/user-attachments/assets/c6f3e16b-19fc-4314-b9b3-bf586abc4457

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
What is full dialog appear in background before showing sync dialog?

**Comment by akashmeruva9** [comment]
> What is full dialog appear in background before showing sync dialog?

Sir this dialog should be called from a Compose Screen, but since @Aditya-gupta99 is still working on the compose migration of the settings Activity, I called this from the previous Dialog Fragment. That's y we can see the background appear.

**Comment by therajanmaurya** [comment]
I merged his PR, make the changes and let me know so I can review and merge your PR as well.

**Comment by akashmeruva9** [comment]
> I merged his PR, make the changes and let me know so I can review and merge your PR as well.

Ok sir, will try to make the changes

**Pull request merged**
